project:
  title: "data-science-templates"

format:
  html:
    fig-width: 12
    fig-height: 8
    fig-align: center
    warning: false
    embed-resources: true

editor_options: 
  chunk_output_type: console