project:
  title: "data-science-templates"

format:
  html:
    warning: false
    embed-resources: true
    page-layout: full
    fig-width: 12
    fig-height: 8
    fig-align: center
    code-copy: true

editor_options: 
  chunk_output_type: console
  