---
title: "R vs Python"
subtitle: "Considering the Age Old Language Wars & Choosing the 'Right' Language"
author: "Paul Johnson"
date: "`r Sys.Date()`"
---

R and Python are two of the most popular programming languages in the world, and they are both used extensively in data science. However, there is a lot of debate about which language is better, and which language is more suitable for data science. A quick Google search for "R vs Python" will quickly point you in the direction of plenty of strongly-held opinions about why R or Python is better and why the other language is rubbish and a total waste of time, but I think these debates are a little worn out, and it doesn't help newcomers to the field to see these dichotomous views of two of the most popular languages for data science out there.

In my view, as someone that started out with R before moving on to Python, and that is comfortable using either, I don't think the most important decision is about which language you will learn. It's the decision to learn any programming language at all. I've found that different people find different languages easier to get started with. Personally, I find that Python makes a little more sense to me than R. While I've been using R a lot longer, and am quite capable with it (perhaps more so than I am with Python), I tend to be able to learn methods/concepts easier with Python, because the logic that underpins Python methods just works for me. But that doesn't mean that the logic underpinning Python is better. It just happens to be the case that it is well-aligned with the way that I think about programming. I think it is more important to find which language makes the most sense to you. Both are very strong on data science, as well as being strong in a number of other areas, and both are very popular. Playing around with them both and working out which one makes most sense to you, and which one gives you the best shot at maintaining your coding journey, is what matters.

It's also worth noting that learning a second language, when you are confident with your first, is a lot easier. The hard part is learning the first language. If you crack that part, then you will be able to tackle the second, third, and fourth languages with a lot more ease and at a much faster pace. Learning R doesn't mean you have to stick to R forever, and vice versa for Python. The important thing is that you've learned a coding language. **Any** coding language.

## Design Principles

The design principles that underpin a programming language can have an impact on how the language works, how easy it is to learn, and how easy it is to use. Although these principles are not vital for beginners to understand, they can be useful for understanding why some languages are better suited to certain tasks than others, and what the differences are between languages like R and Python.

One of the key similarities between the two languages is that they are both interpreted languages. This means that they are not compiled before they are run, and this makes them easy to use, and it makes them a good choice for beginners. The downside of interpreted languages is that they are slower than compiled languages. This is not an issue for most data science tasks, especially when you are first starting out, but it is something to be aware of if you are working with very large datasets. For more information about the differences between interpreted and compiled languages, this article from [freeCodeCamp](https://www.freecodecamp.org/news/compiled-versus-interpreted-languages/) is a good overview.

While both R and Python are interpreted languages, there are a number of differences between both, in terms of the design principles that underpin each language, and these differences impact how each language works and how you write code in them. R is a [functional programming](https://www.freecodecamp.org/news/an-introduction-to-the-basic-principles-of-functional-programming-a2c2a15c84/) language, which means that you can pass functions as arguments to other functions, and you can return functions from other functions, Python is an [object-oriented programming](https://www.freecodecamp.org/news/object-oriented-programming-concepts-21bb035f7260/) (OOP) language. This means that you can pass objects as arguments to other functions, and you can return objects from other functions. This distinction is probably not something that you need to worry about when you are first starting out on your coding journey, but if you want to master either language, it's important to understand their design principles and how this affects the way that you write code. For a more in-depth discussion about the differences between functional and object-oriented programming, see this [blog post](https://www.educative.io/blog/functional-programming-vs-oop) by Tate Dorman at Educative.io.

There are also some differences in terms of the data structures that are commonly used in each language, and the libraries that are available in R and Python also impact what is possible in either language, and which language is better suited to which tasks.

## Data Science Tasks

Both languages can be used to do virtually any data science task. For R, this is because it has been adapted to work for a wide range of tasks, while it is by design that Python can be applied to a wide variety of domains. This is because Python is designed as a general-purpose programming language, while R is designed as a statistical programming language.

For this reason, R tends to be better at statistical analysis. In addition to R's strength as a statistical programming language, there are also packages that add to R's functionality, and are arguably the strongest part of the R ecosystem. The [tidyverse](https://www.tidyverse.org/), a collection of open source packages for R that "share an underlying design philosophy, grammar, and data structures" of tidy data, have turned R into a language that excels when it comes to data manipulation and wrangling and data visualisation. The tidyverse package, [`dplyr`](https://dplyr.tidyverse.org/) (in conjunction with [`readr`](https://readr.tidyverse.org/) for importing data and [`tidyr`](https://tidyr.tidyverse.org/) for tidying data) is a powerful tool for data manipulation, while [`ggplot2`](https://ggplot2.tidyverse.org/) is a brilliant data visualisation package.

Python, on the other hand, excels in a number of areas, but its biggest strength is that it is capable of doing basically anything _reasonably_ well. This owes to Python's design as a general-purpose programming language. Python tends to be the language of choice for machine learning and deep learning, and it has a very mature ecosystem of libraries for these tasks. Python also has a number of libraries that are useful for web development and data engineering, and it is a good choice for building data-driven web applications and APIs, and for building data pipelines.
