---
title: "A Scientific Approach to Solving Problems"
subtitle: "The Importance of Doing Data Science the 'Right Way'"
author: "Paul Johnson"
date: today
---

While it is important to learn the methods detailed in these guides (and more), the greatest emphasis should be placed on learning how to use the scientific method to approach problems. Approaching business problems scientifically, trying to build theories based on our observations about the subject being studied, is often overlooked, as this is in many ways the most complex part of the process. It is also less exciting than learning new ways to analyse data, so for someone that is new to data science, it is quite easy to deemphasise this and focus on doing the fun parts instead.

These issues are exacerbated by the fact that any data science education, whether formal or self-taught, is often focused on the methods and tools required for data science. There is less explicit focus on the "process", but this is because the process is taught implicitly through the methods. Teaching the various methods and tools that a data scientist needs to know is time-consuming and complex, and in the process of learning and applying the methods, the student will also learn the scientific approach to problem solving. That said, once someone has mastered the methods, they are (relatively) east to apply to real-world problems, while the process of doing science the right way is more difficult, and requires careful consideration for every practicioner, no matter how experienced they are.

## Framing the Problem

All of this ties into the same questions that should be asked when identifying data science opportunities. But having identified these opportunities, it is important not to skip to identifying a cool method for solving the problem. Instead, focus on the problem itself, and then identify the method(s) that will be most appropriate for answering it.

A simple, concise approach to framing the problem and maximising the value of data science is to use Tom Carpenter's suggestions below:

{{< tweet tcarpenter216 1646304103004504064 >}}

If you follow these five steps detailed by Tom, you stand a good chance of approaching the problem in the right way, generating real business value, and really getting to the heart of the problem you are trying to solve.

## A Simple Framework for Data Science

The guides here obviously focus on the methods, but before diving into the code, I think it is important to highlight the importance of learning to implement these methods appropriately, and approaching data science in the "correct" way. This means understanding the problem, generating theories about how to solve it, identifying the data that is needed to test these theories, and building a robust model that is informed by your theory and that is appropriate for the data you have. Before jumping into the code and the iterative process of model building, it is important to take the time to think carefully about your theory, the variables that are relevant to the phenomenon you are studying and the causal mechanism that guides it (or the data generating process), and your expectations from your model. Only once you've thought carefully about all of these things should you start to think about the method(s) you should use.

### The Best-Case Scenario

The order of these steps is important, but the right order is dependent on context. In the perfect world, where all data is readily available and free from privacy concerns, and everybody has nothing but time to spend building the most robust models possible, the order would be as follows:

1. Problem - Every data science project should start with the identification of a problem that needs to be solved or a question that needs to be answered. Perhaps you've observed a phenomenon that you want to understand, like the role that deprivation plays in health outcomes. The first step is framing this phenomenon as a problem or a question, for which you can develop a solution. In this case, the question might be "how does deprivation affect health outcomes?".
2. Theory - The theory should be the starting point in the process of developing your solution. The theory should be informed by your understanding of the problem you are studying (potentially including studying existing research in this area). What your theory should look like depends on what you are trying to do.
   - Explanation (Causal Inference) - If you are trying to explain something, like the relationship between deprivation and health outcomes, your theory should seek to identify the causal mechanism that explains the relationship. In this case, the theory might be that deprivation has a negative effect on health outcomes because of a lack of access to high-quality healthcare resources, or because of the negative effects of air quality and lack of green spaces in deprived areas.
   - Prediction (Machine Learning) - If the goal is predicting outcomes, the theory should still drive the process, but in this case the causal mechanism might take less of a priority. The goal is to identify the factors that will contribute to the best predictions, and the role of the theory-building process is to identify these factors. While thinking about the causal mechanism that leads one variable to affect another will help identifying the relevant factors that should go into the model, it's not the central focus when trying to predict outcomes.
3. Method - Having developed a theory, it's now possible to identify the appropriate method(s) for testing it (although with machine learning you are not exactly "testing" the theory). This might look like an experiment, a regression, or a gradient boosting model, depending on what you are trying to achieve, but the method you choose should be informed by your theory. In any case, it is unlikely that you will be able to design the methodology with complete precision at this stage (especially when it comes to machine learning), however, you should have a good idea of the approach you intend to take to test your theory.
4. Data - Whether or not your data collection should come before or after the method selection stage of the process is highly dependent on context, but in the fantasy world where we're awash with good quality and readily available data, the data collection would happen after you've designed your research method. This is especially important when it comes to causal inference.
5. Model - Finally, having developed your theory, identified a method for testing it, and collected the data you need to do so, you can now build your model. This will often be an iterative process, informed by the results of the model, model validation and testing, and data exploration. But this entire process should be informed by your theory. When trying to explain a phenomenon, the goal should be to build a model that is the most precise representation of the phenomenon you are studying, rather than actively seeking to build a model that confirms your theory (this is **very important**). On the other hand, if the goal is prediction, the iterative process of building your model will focus on improving the predictive performance of the model.

### The Real World

In reality, the process is rarely this clean. Data is messy (if it exists at all), time is limited, and the process is informed by multiple competing interests. Scientific research is driven by the need to be as precise as possible (or the publish or perish grind, depending on how cynical a view you want to take), building models that are as close to the true data generating process as possible. In industry, precision is just one of a number of important concerns, including time, cost, scalability, and interpretability. Perhaps the driving force behind this difference is that in industry you are seeking to "solve a problem". The advancement of human knowledge might be a positive externality of the process, but the focus is on building solutions for business problems, and precision is not the only factor when trying to fix a problem.

Nonetheless, I think the above framework is a helpful guide for approaching data science. It is often helpful to think about the ideal approach you would take, and then adapt it to the circumstances you find yourself in, and the simple framework detailed above is a a broad overview of what an "ideal" approach might look like.

Given the limitations that being forced to exist in the real world imposes on our work, the theory-building, method selection, and data collection steps in the process are often iterative, or overlapping. It is often necessary to identify what data is available for solving the problem, before carrying out exploratory analysis to refine your theory and decide on the method for your analysis. This may even mean that, having considered the availability, reliability, and quality of the relevant data, the problem cannot be solved. Being able to identify when this is the case, instead of plowing ahead with a model that is doomed to failure, or worse, a model that will produce misleading or inaccurate results, is equally as important as being able to identify the right methods given an abundance of data.

The important takeaway, however, is that the process matters, and that the method, no matter how fancy, is just one part of the process.

## Avoiding the Nerd Trap

For anyone that is analytically minded, it is very easy to fall into the trap of hyperfocusing on the cool methodological approaches you could take to solving a problem. This is something that I regularly have to check myself on, because I find it so easy to get excited about the fancy methods I could apply to a particular situation. However, despite the fact that the methods are often the most fun part of the job, the fact remains that a very fancy model won't get you very far if you haven't spent a lot of time thinking carefully about the problem that model is trying to solve, gathering the data that is needed to solve it, and preparing the data in a way that maximises the model's performance.

The easiest way to avoid falling into the same trap that I regularly slip into is to treat the methods as a means to an end. The goal should always be to build a solution to a specific problem, with a clear understanding of what "success" looks like in that context. And if you also get to make something fancy in the process? Well isn't that exciting!

## Resources

- [Key Skills for Aspiring Data Scientists: Problem Solving and the Scientific Method](https://faculty.ai/blog/key-skills-for-aspiring-data-scientists-problem-solving-and-the-scientific-method/)
- [Richard Feynman on the Scientific Method](https://research-training-centre.sps.ed.ac.uk/feynman-scientific-method-and-sociology/)
