project:
  output-dir: _book_python
  execute-dir: file

book:
  title: "Python Data Science Guides"
  page-footer:
    center: |
      <a href="https://r-data-science-guides.netlify.app">
      R Data Science Guides</a> {{< fa brands r-project size=xl >}}

  chapters:
    - index.qmd
    - intro.qmd
    - good_science.qmd

    - part: "Dealing with Data"
      chapters:
        - sql.qmd
        - eda_py.qmd

    - part: "Statistical Inference"
      chapters:
        - linear_regression_py.qmd
    - part: "Machine Learning"
    - part: "Deep Learning"
    - part: "Delivering Data Science"

  appendices:
    - installing_python.qmd
    - version_control.qmd

bibliography: references.bib
