<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>R Data Science Guides - 6&nbsp; Hypothesis Testing</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./linear_regression_r.html" rel="next">
<link href="./eda_r.html" rel="prev">
<link href="./figures/favicon.ico" rel="icon">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/quarto-contrib/fontawesome6-0.1.0/all.css" rel="stylesheet">
<link href="site_libs/quarto-contrib/fontawesome6-0.1.0/latex-fontsize.css" rel="stylesheet"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>
</head>
<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./hypothesis_testing_r.html">Statistical Inference</a></li><li class="breadcrumb-item"><a href="./hypothesis_testing_r.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Hypothesis Testing</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="./index.html" class="sidebar-logo-link">
      <img src="./figures/scw_logo.jpg" alt="" class="sidebar-logo py-0 d-lg-inline d-none"></a>
    <div class="sidebar-title mb-0 py-0">
      <a href="./">R Data Science Guides</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/NHS-South-Central-and-West/data-science-guides/tree/main/book/" rel="" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./good_science.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Doing Good Science</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">Dealing with Data</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./sql.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Importing Data from SQL</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./wrangling_r.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Wrangling Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./eda_r.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Exploratory Data Analysis</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
 <span class="menu-text">Statistical Inference</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./hypothesis_testing_r.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Hypothesis Testing</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./linear_regression_r.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Linear Regression</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
 <span class="menu-text">Machine Learning</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ml_workflow_r.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">End-to-End Machine Learning Workflow</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Deep Learning</span></span>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Delivering Data Science</span></span>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./installing_r.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Installing R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./version_control.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Version Control</span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li><a href="#the-old-way-of-doing-things" id="toc-the-old-way-of-doing-things" class="nav-link active" data-scroll-target="#the-old-way-of-doing-things"><span class="header-section-number">6.1</span> The Old Way of Doing Things</a></li>
  <li>
<a href="#the-problems-with-hypothesis-testing" id="toc-the-problems-with-hypothesis-testing" class="nav-link" data-scroll-target="#the-problems-with-hypothesis-testing"><span class="header-section-number">6.2</span> The Problems With Hypothesis Testing</a>
  <ul class="collapse">
<li><a href="#p-values-statistical-significance" id="toc-p-values-statistical-significance" class="nav-link" data-scroll-target="#p-values-statistical-significance"><span class="header-section-number">6.2.1</span> P-Values &amp; Statistical Significance</a></li>
  <li><a href="#garden-of-forking-paths" id="toc-garden-of-forking-paths" class="nav-link" data-scroll-target="#garden-of-forking-paths"><span class="header-section-number">6.2.2</span> Garden of Forking Paths</a></li>
  <li><a href="#comparisons-are-not-enough" id="toc-comparisons-are-not-enough" class="nav-link" data-scroll-target="#comparisons-are-not-enough"><span class="header-section-number">6.2.3</span> Comparisons Are Not Enough</a></li>
  </ul>
</li>
  <li>
<a href="#avoiding-the-pitfalls" id="toc-avoiding-the-pitfalls" class="nav-link" data-scroll-target="#avoiding-the-pitfalls"><span class="header-section-number">6.3</span> Avoiding the Pitfalls</a>
  <ul class="collapse">
<li><a href="#improving-hypothesis-testing" id="toc-improving-hypothesis-testing" class="nav-link" data-scroll-target="#improving-hypothesis-testing"><span class="header-section-number">6.3.1</span> Improving Hypothesis Testing</a></li>
  <li><a href="#moving-beyond-testing" id="toc-moving-beyond-testing" class="nav-link" data-scroll-target="#moving-beyond-testing"><span class="header-section-number">6.3.2</span> Moving Beyond Testing</a></li>
  </ul>
</li>
  <li>
<a href="#building-statistical-tests" id="toc-building-statistical-tests" class="nav-link" data-scroll-target="#building-statistical-tests"><span class="header-section-number">6.4</span> Building Statistical Tests</a>
  <ul class="collapse">
<li><a href="#t-tests" id="toc-t-tests" class="nav-link" data-scroll-target="#t-tests"><span class="header-section-number">6.4.1</span> T-Tests</a></li>
  <li><a href="#chi-squared-tests" id="toc-chi-squared-tests" class="nav-link" data-scroll-target="#chi-squared-tests"><span class="header-section-number">6.4.2</span> Chi-Squared Tests</a></li>
  <li><a href="#simulation-based-statistical-tests" id="toc-simulation-based-statistical-tests" class="nav-link" data-scroll-target="#simulation-based-statistical-tests"><span class="header-section-number">6.4.3</span> Simulation-Based Statistical Tests</a></li>
  </ul>
</li>
  <li><a href="#next-steps" id="toc-next-steps" class="nav-link" data-scroll-target="#next-steps"><span class="header-section-number">6.5</span> Next Steps</a></li>
  <li><a href="#resources" id="toc-resources" class="nav-link" data-scroll-target="#resources"><span class="header-section-number">6.6</span> Resources</a></li>
  </ul><div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/NHS-South-Central-and-West/data-science-guides/issues/new" class="toc-action">Report an issue</a></p><p><a href="https://github.com/NHS-South-Central-and-West/data-science-guides/blob/main/book/hypothesis_testing_r.qmd" class="toc-action">View source</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title"><span id="sec-hypothesis-testing" class="quarto-section-identifier"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Hypothesis Testing</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header><!-- links used throughout the book --><!-- hypothesis testing --><!-- simulations --><div class="cell">
<details><summary>Setup Code (Click to Expand)</summary><div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># packages needed to run the code in this section</span></span>
<span><span class="co"># install.packages(c("dplyr", "tidyr", "faux", "ggplot2", "infer", "remotes"))</span></span>
<span><span class="co"># remotes::install_github("NHS-South-Central-and-West/scwplot")</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/message.html">suppressPackageStartupMessages</a></span><span class="op">(</span><span class="op">{</span></span>
<span>  <span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://dplyr.tidyverse.org">dplyr</a></span><span class="op">)</span></span>
<span>  <span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://ggplot2.tidyverse.org">ggplot2</a></span><span class="op">)</span></span>
<span>  <span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/tidymodels/infer">infer</a></span><span class="op">)</span></span>
<span><span class="op">}</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># set plot theme</span></span>
<span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/theme_get.html">theme_set</a></span><span class="op">(</span><span class="fu">scwplot</span><span class="fu">::</span><span class="fu"><a href="https://nhs-south-central-and-west.github.io/scwplot/reference/theme_scw.html">theme_scw</a></span><span class="op">(</span>base_size <span class="op">=</span> <span class="fl">14</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># set random seed</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">123</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>This chapter will cover a topic that is well known to many practitioners - hypothesis testing. Hypothesis testing remains widely used, despite the dominant strain of this method, Null Hypothesis Significance Testing (NHST), facing growing (though not new) criticisms regarding it’s external validity. If you have ever come across discussions about the “replication crisis” in science, you will have read about the many issues concerning the use of statistical significance as a measure of evidence in science and the misunderstanding and misuse of p-values. The null hypothesis significance testing framework is another of the central culprits in this crisis.</p>
<p>Hypothesis testing may be one of the most prominent tools for statistical inference, but there is plenty of debate about how we should be doing it, and whether the method should be consigned to the history books of statistics, only to be remembered as that silly time in our lives when we used to do science really badly. Here I hope to be able to give readers a clear understanding of how hypothesis testing works, it’s biggest drawbacks, and some advice about how to carry out robust tests of hypotheses.</p>
<!-- In the interest of honesty and transparency, I think we should use hypothesis tests sparingly, and I think that null hypothesis significance testing is most responsible for the issues faced in science. However, I also recognise that this approach is not going away, so I think it is important to discuss hypothesis testing here. It is a commonly used method in academia and in industry, and I think these guides should meet the needs of reality, instead of trying to find a place in a fantasy where hypothesis testing doesn't exist. -->
<p>Beyond this, I will make a case for moving away from hypothesis testing and towards the estimation of effect sizes. In doing so, I will demonstrate how to carry out some common statistical tests, using the guidelines in this chapter to inform how tests are carried out and how the results are presented. I will attempt to thread the needle between caution and clarity<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>, but I recognise that this is not easy, and I’m not sure how successfully I will manage it!</p>
<section id="the-old-way-of-doing-things" class="level2" data-number="6.1"><h2 data-number="6.1" class="anchored" data-anchor-id="the-old-way-of-doing-things">
<span class="header-section-number">6.1</span> The Old Way of Doing Things</h2>
<p>A hypothesis is a statement about an effect that we expect to observe in our sample data, that is intended to generalise to the population. We do not know what the true effect in the population is, but we have a theory about what it might be, and we can test that theory using a hypothesis about what we will observe in the sample. Our hypothesis might relate to how the mean value of a certain quantity of interest (like height) differs from one group to another, or how we expect the value of one quantity in our sample to change as the value of another quantity changes (like the effect of weight on height). A hypothesis test is a statistical method for empirically evaluating a hypothesis, to determine whether what we observe in our sample data is likely to exist in the population.</p>
<p>The most common approach to testing hypotheses is the Null Hypothesis Significance Testing (NHST) framework. The goal of NHST is to “adjudicate between two complementary hypotheses” <span class="citation" data-cites="blackwell2023">(<a href="references.html#ref-blackwell2023" role="doc-biblioref">Blackwell 2023</a>)</span>, the null hypothesis (<span class="math inline">\(H_0\)</span>) and the alternative/research hypothesis (<span class="math inline">\(H_1\)</span>). The null hypothesis, which is the hypothesis that no effect exists in the population, is our starting assumption, and we require strong evidence to reject it. If we are able to find strong enough evidence to reject the null, this moves us one step closer to making a case for our alternative hypothesis.</p>
<p>The reasoning for using two complementary hypotheses is based on <span class="citation" data-cites="popper1935">Popper (<a href="references.html#ref-popper1935" role="doc-biblioref">1935</a>)</span>’s <em>The Logic of Scientific Discovery</em>. Popper argues that it is impossible to confirm a hypothesis, because hypotheses are a form of inductive reasoning, which involves drawing conclusions about a general principle based on specific observations. We cannot confirm a hypothesis because we cannot prove that it is true by generalising from specific instances. However, we <em>can</em> falsify a hypothesis. If what we observe in our sample provides strong evidence that our hypothesis cannot be true, then we can conclude (with a degree of certainty) that the hypothesis is false.</p>
<p>For a better understanding about the null and alternative hypothesis, I would recommend Josh Starmer’s StatQuest videos, embedded below:</p>
<div class="quarto-video ratio ratio-16x9"><iframe data-external="1" src="https://www.youtube.com/embed/0oc49DyA3hU?si=wDuNFfgpP4hQml8e" title="" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe></div>
<div class="quarto-video ratio ratio-16x9"><iframe data-external="1" src="https://www.youtube.com/embed/5koKb5B_YWo?si=ydyTZguZATS9wehl" title="" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe></div>
<p>When we carry out a hypothesis test, we are quantifying our confidence that what we observe in the sample did not occur by chance. If we are able to show that a effect is extremely unlikely to have occurred by chance, we can reject the null hypothesis. Rejecting the null doesn’t demonstrate that the observed effect can be explained by our theory, however, demonstrating that the observed data does not conform to our expectations given that all of our test’s assumptions, including the null hypothesis, are true, moves us one step closer to supporting our theory.</p>
<!-- ## Testing a Hypothesis -->
<!-- Suppose we have a theory that a treatment has a positive effect on a particular medical condition, such as diabetes. We can test this theory by giving a group of diabetics the treatment and observing what happens. We can't observe the counterfactual, which means we can't be certain that any positive (or negative) effect occurred as a result of the treatment, or by chance (or some other factor that hasn't been accounted for), so we would also include a control group of diabetics that don't receive the treatment. This control group acts as a comparison, and we would randomise the process for selecting the people in both groups, in order to reduce the risk that some other factor is impacting our results, in an attempt to approximate the counterfactual. If we observe that treatment group's condition improves, while the control group's condition does not, we might be tempted to conclude that the treatment is responsible for this difference. However, there are all manner of explanations for why this difference might have occurred. Perhaps everyone in our treatment group is actually incredibly lucky, or those in the control group are incredibly unlucky. Demonstrating that there is a difference between the two groups, no matter how large, is not directly proving our theory that the treatment caused it.  -->
<!-- Our alternative hypothesis, in this situation, is that the mean difference between the treatment and control groups is greater than zero, and our null hypothesis is that the mean difference between the treatment and control groups will be equal to zero. We can then carry out our experiment and measure the difference between the two groups, testing these hypotheses. -->
<!-- The final step in the process involves measuring this difference and quantifying our confidence that these differences did not occur by chance. If we are able to show that the difference is extremely unlikely to have occurred by chance, we can reject the null hypothesis that the mean difference between the treatment and control groups is zero, and if we are not able to do this, we are unable to reject the null hypothesis, so we cannot be confident that what we've observed was not generated by chance. Rejecting the null doesn't demonstrate that the difference was caused by the treatment.[^Null] Instead, if our theory is a robust, logical explanation of how the treatment might cause a positive response in diabetics, the results lend support to our theory. If we have carried out or experiment under robust, careful conditions (like a randomised controlled trial) that do as much as possible to limit the counterfactual explanations for the difference between the treatment and control group, the result lends strong support to our theory. It is only through multiple independent evaluations that all draw the same conclusion that we can approach a consensus that an effect exists and that the theory is correct. -->
<!-- [^Null]:  -->
<!--     Rejecting a null hypothesis is not sufficient support for a particular alternative hypothesis. First -->
<!--     of all, rejecting the null hypothesis is a probabilistic statement, meaning there is a degree of -->
<!--     uncertainty in that rejection. But more importantly (in this context at least), rejecting the null -->
<!--     is not a direct assertion that the alternative is true. There will be multiple different -->
<!--     explanations for a phenomenon, and the stated alternative hypothesis is just one. Demonstrating that -->
<!--     something probably did not occur by chance does not mean that the stated alternative hypothesis is -->
<!--     therefore true. -->
<!--     When thinking about what it is a hypothesis test is trying to achieve, I particularly like the -->
<!--     framing used by @crump2019. They refer to the idea of "confidence". A hypothesis test helps the -->
<!--     practitioner to quantify the amount of confidence they can have in what they observe. I like this -->
<!--     framing because it acknowledges the inherent uncertainty that underpins hypothesis testing. We -->
<!--     cannot be absolutely certain about what we observe, but we might be lucky enough to be relatively -->
<!--     confident about it. -->
<!-- ## How Hypothesis Testing Works -->
<!-- ## Comparing Data With a Theoretical Distribution -->
<!-- This expression says that the rejection region is the part of the sample space that makes the test statistic sufficiently large. We reject null hypotheses when the observed data is incompatible with those hypotheses, where the test statistic should be a measure of this incompatibility. Note that the test statistic is a random variable and has a distribution—we will exploit this to understand the different properties of a hypothesis test. -->
<!-- If we have an alternative hypothesis and a null hypothesis, we can carry out a hypothesis test to see if we can reject the null hypothesis. We do this using a test statistic, which measures the difference between the observed data (using some summary measure of the data like the mean value) and our approximation of what we would expect to observe if the null hypothesis was true (the null distribution). Having calculated our test statistic, we are then able to convert this to a p-value, which represents the probability of getting a test statistic at least as large as the one observed if the null hypothesis were actually true. -->
<!-- There are a wide variety of statistical tests that can compute a test statistic and the corresponding p-value. In this section we will focus on tests of significance, which attempt to measure whether the difference in means between groups is statistically significant (unlikely to have occurred by chance). The differences between the many significance tests tends to be a cause of some confusion for new-learners, but I find it easier to first understand their similarities, and build an understanding about how they differ from there. .  -->
<!-- Constructing a null distribution (whether normal, $t$, $F$, or $\chi^2$ distributions) is useful because the shape and size of the distribution is known (given parameters such as mean and standard deviation), which allows us to ask what the data would look like if it was generated by chance. Having done this, we can compare our sample mean against the null distribution and ask how often we would expect to observe this mean value if the data was in fact generated by chance. In a broad sense, test statistics are all trying to measure the ratio of effect size and error in a particular sample [@crump2019].  -->
<!-- Statistical tests can ask this question of data sampled from a single group, comparing it against a null distribution that represents what we would expect if this data was generated by chance; while others may ask this question of two groups of data, computing the mean difference between the groups and comparing this against the null distribution that we would expect to observe if there was no difference between the two groups; and finally, some tests ask this question of data sampled from multiple groups, computing summary statistics of each group and comparing whether the within-group structure varies significantly to the between-group structure of the data. -->
<!-- Every test statistic is a representation of the data distribution, and the choice of different test statistics is dependent on the type of data you are dealing with. Statistical tests are just the way that you calculate the test statistic and convert that statistic to a p-value. -->
<!-- "The distance between the data and the model predictions is measured using a test statistic (such as a t-statistic or a Chi-squared statistic). The p-value is then the probability that the chosen test statistic would have been at least as large as its observed value if every model assumption were correct, including the test hypothesis." [@greenland2016, pp. 339] -->
<!-- "In logical terms, the P value tests all the assumptions about how the data were generated (the entire model), not just the targeted hypothesis it is supposed to test (such as a null hypothesis)." [@greenland2016, pp. 339] -->
<!-- "It is true that the smaller the P value, the more unusual the data would be if every single assumption were correct; but a very small P value does not tell us which assumption is incorrect. For example, the P value may be very small because the targeted hypothesis is false; but it may instead (or in addition) be very small because the study protocols were violated, or because it was selected for presentation based on its small size. Conversely, a large P value indicates only that the data are not unusual under the model, but does not imply that the model or any aspect of it (such as the targeted hypothesis) is correct; it may instead (or in addition) be large because (again) the study protocols were violated, or because it was selected for presentation based on its large size." [@greenland2016, pp. 339] -->
<!-- First, lets start with the American Statistical Association's (ASA) definition of a p-value, as given in their official statement on the use of p-values in 2016. The ASA defines a p-value as "the probability under a specified statistical model that a statistical summary of the data (e.g., the sample mean difference between two compared groups) would be equal to or more extreme than its observed value [@wasserstein2016]. 

There are definitely cleaner, more concise definitions of p-values out there, but one of the biggest issues surrounding p-values in statistics and across the sciences is that they have been misused, misunderstood, and misspecified for so long that it can sometimes be a little difficult to be certain about what is and isn't correct about p-values, even when you find it in what otherwise looks like a credible source. -->
<!-- P-Values represent a "statistical summary of the compatibility between the observed data and what we would predict or expect to see if we knew the entire statistical model (_all_ the assumptions used to compute the p-value) were correct". [@greenland2016, 339]

The "distance between the data and the model prediction is measured using a _test statistic_". The p-value is "the probability that the chosen test statistic would have been _at least_ as large as its observed value if _every_ model assumption were correct, including the test hypothesis". [@greenland2016, 339]

@greenland2016 stress the importance of recognising that testing _all_ of the model's assumptions is not the same as testing only the targeted hypothesis (often the null). These assumptions include the targeted hypothesis, the assumptions required for the statistical test itself, and assumptions about the choices made in the analysis. 

This is something that is often missed when talking about p-values. Small p-values are indication that the data is unusual, but only given that all assumptions are correct, and the p-value does not tell us which assumptions are incorrect. -->
</section><section id="the-problems-with-hypothesis-testing" class="level2" data-number="6.2"><h2 data-number="6.2" class="anchored" data-anchor-id="the-problems-with-hypothesis-testing">
<span class="header-section-number">6.2</span> The Problems With Hypothesis Testing</h2>
<p>Hypothesis testing is and will remain an important part of science. We use hypothesis testing to sift through noise in data to dry and draw conclusions, and this is a perfectly reasonable goal. However, the dominant framework for testing hypotheses, Null Hypothesis Significance Testing, is rife with issues. Unfortunately, while there is a growing consensus about some of the issues with hypothesis testing, that doesn’t mean this debate is settled, and it certainly doesn’t mean the path forward is clear. The discussion is ongoing, and while I believe I am giving a reasonably good representation of the summary points that have shaken out so far, I’m sure you would be able to find many, many very smart people that disagree with me on much of what is said. The uncomfortable truth is that this stuff is really hard, and we haven’t reached a consensus on the best way to do hypothesis testing (or whether we should do it at all).</p>
<section id="p-values-statistical-significance" class="level3" data-number="6.2.1"><h3 data-number="6.2.1" class="anchored" data-anchor-id="p-values-statistical-significance">
<span class="header-section-number">6.2.1</span> P-Values &amp; Statistical Significance</h3>
<p>The biggest problems with NHST relate to the misuse and misunderstanding of p-values, and their dichotomisation in order to make arbitrary judgements about statistical significance. The extent of the issues surrounding p-values and statistical significance are so extensive that it led the American Statistical Association to make an official statement addressing the misconceptions and clarifying the correct usage of p-values <span class="citation" data-cites="wasserstein2016">(<a href="references.html#ref-wasserstein2016" role="doc-biblioref">Wasserstein and Lazar 2016</a>)</span>. The statement makes the point that p-values do not measure the probability that a hypothesis is true, or that the data was produced by random chance alone; nor should they be interpreted as measuring the size of an effect or the importance of a result; and that by themselves p-values are not a good measure of the evidence for a model or a hypothesis <span class="citation" data-cites="wasserstein2016">(<a href="references.html#ref-wasserstein2016" role="doc-biblioref">Wasserstein and Lazar 2016</a>)</span>. Unfortunately, these are all very common misconceptions that find their way into scientific research. The misconceptions go much further than this, however, as illustrated by <span class="citation" data-cites="greenland2016">Greenland et al. (<a href="references.html#ref-greenland2016" role="doc-biblioref">2016</a>)</span>. <span class="citation" data-cites="greenland2016">Greenland et al. (<a href="references.html#ref-greenland2016" role="doc-biblioref">2016</a>)</span> build on the wider discussion to include statistical tests, laying out a total of 25 different misconceptions about statistical testing, p-values (and confidence intervals) and statistical power<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>. They make the case that the biggest culprit is the arbitrary use of thresholds for defining statistical significance, which frame p-values in problematic terms, reduce a need for critical thinking about findings, and are far too easily abused.</p>
<p>This discussion has even permeated some of the media <span class="citation" data-cites="aschwanden2015 aschwanden2016">(<a href="references.html#ref-aschwanden2015" role="doc-biblioref">Aschwanden 2015</a>, <a href="references.html#ref-aschwanden2016" role="doc-biblioref">2016</a>)</span>. FiveThirtyEight have written about this issue in some detail, and their discussion of the topic is perhaps more accessible than the more detailed discussions going on. <span class="citation" data-cites="aschwanden2015">Aschwanden (<a href="references.html#ref-aschwanden2015" role="doc-biblioref">2015</a>)</span> is a particularly good summary of the discussion around p-values, and does a good job highlighting that the issues around p-values and the “replication crisis” are not evidence that science can’t be trusted, but rather that this stuff is extremely difficult, and that it takes a community of scientists working towards the truth, to try and achieve results.</p>
</section><section id="garden-of-forking-paths" class="level3" data-number="6.2.2"><h3 data-number="6.2.2" class="anchored" data-anchor-id="garden-of-forking-paths">
<span class="header-section-number">6.2.2</span> Garden of Forking Paths</h3>
<p><span class="citation" data-cites="gelman2021">Gelman and Loken (<a href="references.html#ref-gelman2021" role="doc-biblioref">2021</a>)</span> add to the discussion by highlighting the role that the “garden of forking paths” approach to analysis, where there are many possible explanations for a statistically significant result, plays in the statistical crisis in science. It’s important to recognise how a scientific hypothesis can correspond to multiple statistical hypotheses <span class="citation" data-cites="gelman2021">(<a href="references.html#ref-gelman2021" role="doc-biblioref">Gelman and Loken 2021</a>)</span>, and to guard against this possibility. This effectively creates a “multiple comparisons” situation, where an analysis can uncover statistically significant results that can be used to support a theory by multiple “forking paths”. A “one-to-many mapping from scientific to statistical hypotheses” can create a situation that is equivalent to p-hacking but without the necessary intent <span class="citation" data-cites="gelman2021">(<a href="references.html#ref-gelman2021" role="doc-biblioref">Gelman and Loken 2021</a>)</span>.</p>
<p>One of the central questions that <span class="citation" data-cites="gelman2021">Gelman and Loken (<a href="references.html#ref-gelman2021" role="doc-biblioref">2021</a>)</span> ask, is whether the same data-analysis decisions would have been made with a different data set. The garden of forking paths is driven by the fact that we devise scientific hypotheses using our common sense and domain knowledge, given the data we have, and we do not consider the myriad implicit choices that this involves. By not considering these implicit choices, we fail to account for the garden of forking paths.</p>
</section><section id="comparisons-are-not-enough" class="level3" data-number="6.2.3"><h3 data-number="6.2.3" class="anchored" data-anchor-id="comparisons-are-not-enough">
<span class="header-section-number">6.2.3</span> Comparisons Are Not Enough</h3>
<p>I think that the biggest issue with p-values themselves is that we have placed far too much value in them. We use methods that are designed to compute p-values, we define “success” as the discovery of a statistically significant finding, and we give little thought to the design choices made in the process of carrying out these tests. This is partly driven by the frequency of misconceptions and misunderstandings of p-values, but it’s also a result of the methods we use. If we are more precise about how we think about p-values, this should help us avoid making the mistake of thinking they are proving a hypothesis or that they are sufficient evidence for a theory, but if we are more precise about what a p-value really represents, this raises significant questions about the methods we use. What purpose does a test for “statistical significance” serve if we acknowledge that p-values are not enough? <span class="citation" data-cites="gelman2016">Gelman (<a href="references.html#ref-gelman2016" role="doc-biblioref">2016</a>)</span> argue that p-values are not the real problem, because the real problem is null hypothesis significance testing, which they refer to as a “parody of falsificationism in which straw-man null hypothesis A is rejected and this is taken as evidence in favour of preferred alternative B.” The null hypothesis significance testing framework places far too much weight on the shoulders of p-values, and even if we are doing a better job of hypothesis testing (being particularly careful not to make mistakes about how we use p-values), what is it really worth? When we are treating p-values as a part of the wider toolkit, hypothesis tests become less useful.</p>
<p>Ultimately, regardless of the method used, without good scientific reasoning and careful research design, conclusions will be built on weak grounds.</p>
</section></section><section id="avoiding-the-pitfalls" class="level2" data-number="6.3"><h2 data-number="6.3" class="anchored" data-anchor-id="avoiding-the-pitfalls">
<span class="header-section-number">6.3</span> Avoiding the Pitfalls</h2>
<p>There has been plenty of ink spilled on the topic of what practitioners should not do when it comes to p-values, and while there is no detail too minor for two academics to throw hands over, there is a general consensus that our approach to p-values is a problem. What has not been settled, however, is what the right approach is. That makes this section of this chapter a little trickier. However, I will attempt to give some sensible advice about how to avoid the greatest dangers pose by hypothesis testing and the use of p-values more broadly.</p>
<p>While I do think there are improvements that can be made to the way we approach hypothesis testing that will help us avoid the many pitfalls, I also think the best approach would be to avoid null hypotheses altogether. Instead of trying to devise a test that will calculate the probability of observing our data, if it was generated by chance (and the assumptions of the model are correct), we should be focused on measuring the effect itself, and in the process considering whether we have enough evidence to conclude that this effect is real and meaningful.</p>
<p>However, as stated earlier in this chapter, I recognise that hypothesis testing is not going away. Therefore, I think there are two approaches to avoiding these issues - carrying out better hypothesis tests and choosing better methods than hypothesis tests. The advice here will address these two approaches, though I think the advice for building better tests also applies broadly to how we approach p-values, even when using alternative methods.</p>
<p>So the advice here will first give some general suggestions for how we should approach p-values, which applies to both hypothesis testing and to their alternatives, before talking about those alternatives that I think should take priority.</p>
<section id="improving-hypothesis-testing" class="level3" data-number="6.3.1"><h3 data-number="6.3.1" class="anchored" data-anchor-id="improving-hypothesis-testing">
<span class="header-section-number">6.3.1</span> Improving Hypothesis Testing</h3>
<p>A more general approach to hypothesis testing would frame things in terms of a test hypothesis, which is a hypothesised effect (including but not limited to zero effect – the null hypothesis) that is assumed to be true, and a statistical test is carried out that considers how well the observed date conforms to our expectations given that the test’s assumptions, including the test hypothesis, are true.</p>
<section id="rethink-p-values" class="level4" data-number="6.3.1.1"><h4 data-number="6.3.1.1" class="anchored" data-anchor-id="rethink-p-values">
<span class="header-section-number">6.3.1.1</span> Rethink P-Values</h4>
<p>The p-value is not a magic number. It does not give the probability that your research hypothesis is true, nor does it give the probability that the observed association is a product of random chance <span class="citation" data-cites="wasserstein2019">(<a href="references.html#ref-wasserstein2019" role="doc-biblioref">Wasserstein, Schirm, and Lazar 2019</a>)</span>. One of the biggest issues I have with p-values is that they feel, given the way we use them in the null hypothesis testing framework, like they <strong>should</strong> be the probability that our hypothesis is true. However, it is important to never let those urges win - the p-value is not a hypothesis probability.</p>
<p>Instead, p-values are the degree to which the observed data are consistent with the pattern predicted by the research hypothesis, given the statistical test’s assumptions are not violated <span class="citation" data-cites="greenland2016">(<a href="references.html#ref-greenland2016" role="doc-biblioref">Greenland et al. 2016</a>)</span><a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a>.</p>
<p><span class="citation" data-cites="lakens2022">Lakens (<a href="references.html#ref-lakens2022" role="doc-biblioref">2022</a>)</span> recommends thinking about p-values as a statement about the probability of data, rather than a statement about the probability of a given hypothesis or theory. I think remembering this framing is a good way to avoid misconstruing exactly what p-values represent. Similarly, we can think about p-values as our confidence in what it is we observe in our data. How confident can we be that the data we observed is the product of random chance (and the assumptions that underpin our statistical model)? A p-value is an approximation of this.</p>
<p>The point is that none of these definitions (or more precisely, intuitive explanations) of p-values are claiming that p-values are the probability that the research hypothesis is true. They say nothing about a hypothesis, because they are not a hypothesis probability.</p>
<p>Framing p-values appropriately is one part of the necessary rethink about p-values. The other is the need to place less weight in what p-values tell us. Having acknowledged all the things that p-values are not, this part should be easy to understand. Given that p-values are not a hypothesis probability, and they are really a statement about our data, they are far from sufficient (though I would argue they are at least necessary) for our understanding of our data. Instead, they are part of a wider toolkit. A toolkit that contains even more important tools, like effect sizes!</p>
</section><section id="stop-using-statistical-significance" class="level4" data-number="6.3.1.2"><h4 data-number="6.3.1.2" class="anchored" data-anchor-id="stop-using-statistical-significance">
<span class="header-section-number">6.3.1.2</span> Stop Using Statistical Significance</h4>
<p>In addition to the common misuse of p-values, the null hypothesis significance testing framework also defines an arbitrary threshold for what is considered a sufficiently “meaningful” result - statistical significance.</p>
<p>The commonly defined significance threshold (or the alpha (<span class="math inline">\(\alpha\)</span>) level) is a p-value of 0.05. A p-value of less than 0.05 is deemed statistically significant, while a p-value greater than 0.05 is insignificant. So two p-values, one that equals 0.499 and another that equals 0.501 are both deemed to offer something very different to each other. One is treated as a sign of success, and the other is filed away in the desk drawer, never to be seen again! The arbitrariness of this threshold has been best highlighted by <span class="citation" data-cites="gelman2006">Gelman and Stern (<a href="references.html#ref-gelman2006" role="doc-biblioref">2006</a>)</span> when they demonstrated the fact that the difference between statistically significant and insignificant is not itself statistically significant.</p>
<p>Defining whether a research finding is of real value based on such a meaningless threshold is clearly one of the contributing factors in the problems with hypothesis testing, and the simple solution is to just stop treating p-values as either statistically significant or not!</p>
<p>If you need further evidence of the problems with how we have been using statistical significance, look no further than the man credited with first developing the method, Ronald A Fisher. <span class="citation" data-cites="fisher1956">Fisher (<a href="references.html#ref-fisher1956" role="doc-biblioref">1956</a>)</span> claimed that no researcher has a fixed level of significance that they are using to reject all hypotheses, regardless of their context. Ronald, I have some terrible, terrible news.</p>
<p>Where possible, do not use terms like statistical significance, and do not use a threshold (the <span class="math inline">\(\alpha\)</span> level) for significance. Report p-values instead. P-values should be “viewed as a continuous measure of the compatibility between the data and the entire model used to compute it, ranging from 0 for complete incompatibility to 1 for perfect compatibility, and in this sense may be viewed as measuring the fit of the model to the data.” <span class="citation" data-cites="greenland2016">(<a href="references.html#ref-greenland2016" role="doc-biblioref">Greenland et al. 2016, 339</a>)</span></p>
</section><section id="report-all-findings" class="level4" data-number="6.3.1.3"><h4 data-number="6.3.1.3" class="anchored" data-anchor-id="report-all-findings">
<span class="header-section-number">6.3.1.3</span> Report All Findings</h4>
<p>My final suggestion for how to improve hypothesis testing ties in closely with the previous two suggestions. If p-values are treated like a continuous measure of compatibility, and we are no longer using thresholds to define whether a result is good or bad, this should reduce the urge to report findings selectively, based only on those that say the right thing.</p>
<p>Do not carry out multiple tests and only show the significant results. Be open and transparent about your process and what was tested. Only reporting significant results is problematic for many reasons. There is no reason to favour statistical significant results. Instead, we should either report all our findings, as this is the most transparent approach, or we should select the substantively meaningful results, taking great care to avoid only reporting those that confirm our theory<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a>.</p>
<p>I think this principle is easier to follow in academia, where extensive reporting of findings is encouraged. I don’t think there is a downside to open and transparent reporting in academia (ignoring the potential risks posed to publication). However, in industry, there is often a need to be as clear and concise as possible. Reporting all results could potentially cause confusion, and make statistical findings much harder for non-technical audiences to understand. Therefore I think the advice for industry should be that reporting results should not be defined by the statistical significance of the results. We should report the results that matter, that contribute the most to our understanding of a quantity of interest, and that help others understand the findings. Communication of findings in industry should focus on communicating the key results from the analysis, and that should not be defined by significance.</p>
</section><section id="build-scientific-models" class="level4" data-number="6.3.1.4"><h4 data-number="6.3.1.4" class="anchored" data-anchor-id="build-scientific-models">
<span class="header-section-number">6.3.1.4</span> Build Scientific Models</h4>
<p>Recognise/understand that statistical hypotheses are not the same as scientific hypotheses, and that a statistical hypothesis can often be explained by many different scientific hypotheses.</p>
<p>The garden of forking paths may be a particularly big issue in hypothesis testing, but it doesn’t go away if we scrap the null hypothesis significance tests. We always have to think about how our scientific hypotheses can be explained by multiple statistical hypotheses.</p>
<p>There are so many different assumptions that go into the process of building a statistical model, and when we fail to consider the breadth of assumptions that underpin our work, we can easily invalidate our findings. As discussed earlier in this chapter, we have to remember that p-values are assuming that <strong>all</strong> of our assumptions are true, and if any of them are not true, we are in hot water.</p>
<!-- "A scientific hypothesis in a field such as psychology, economics, or medicine can correspond to any number of statistical hypotheses, and if the ASA is going to issue a statement warning about p-values, I think it necessary to emphasize that researcher degrees of freedom—the garden of forking paths—can and does occur even without people realizing what they are doing. A researcher will see the data and make a series of reasonable, theory-respecting choices, ending up with an apparently successful—that is, 'statistically significant' — finding, without realizing that the nominal p-value obtained is meaningless." [@gelman2016] -->
<!-- "A large p-value only suggests that the data are not unusual if all the assumptions used to compute the p-value (including the test hypothesis) were correct. The same data would also not be unusual under many other hypotheses." [@greenland2016, pp. 341] -->
<p>“All statistical methods (whether frequentist or Bayesian, or for testing or estimation, or for inference or decision) make extensive assumptions about the sequence of events that led to the results presented – not only in the data generation, but in the analysis choices. Thus, to allow critical evaluation, research reports (including meta-analyses) should describe in detail the full sequence of events that led to the statistics presented, including the motivation for the study, its design, the original analysis plan, the criteria used to include and exclude subjects (or studies) and data, and a thorough description of all the analyses that were conducted”. <span class="citation" data-cites="greenland2016">(<a href="references.html#ref-greenland2016" role="doc-biblioref">Greenland et al. 2016, 347</a>)</span></p>
<p>What is needed is to build coherent, logically-specified scientific models from which we design our statistical analysis. <span class="citation" data-cites="mcelreath2023">McElreath (<a href="references.html#ref-mcelreath2023" role="doc-biblioref">2023</a>)</span> makes this case, arguing that we need to build theory-driven scientific models that describe the causal relationship we are modelling before we build statistical models that attempt to test our scientific models.</p>
<p>Building scientific models doesn’t necessarily address all concerns around the “garden of forking paths” issue, but by doing so we are forced to be more thoughtful about our research, and we are more able to identify problems with our analysis.</p>
</section></section><section id="moving-beyond-testing" class="level3" data-number="6.3.2"><h3 data-number="6.3.2" class="anchored" data-anchor-id="moving-beyond-testing">
<span class="header-section-number">6.3.2</span> Moving Beyond Testing</h3>
<p>If a p-value of 0.01 tells us that our results are pretty surprising given our expectations of what the data would have looked like if it was randomly generated (or if we assume that the null hypothesis is true), what should we make of this? How useful, exactly, is knowing this? Well, it depends entirely on the context in which we’ve produced this result, but at most it tells us that our findings are quite surprising.</p>
<section id="estimate-meaningful-quantities" class="level4" data-number="6.3.2.1"><h4 data-number="6.3.2.1" class="anchored" data-anchor-id="estimate-meaningful-quantities">
<span class="header-section-number">6.3.2.1</span> Estimate Meaningful Quantities</h4>
<p>This is, I believe, the most important suggestion that is made in this entire chapter. I am borrowing a phrase used by the UNC Epidemiologist, Charles Poole, in a talk he gave about the value of p-values - “stop testing null hypotheses, start estimating meaningful quantities” <span class="citation" data-cites="poole2022">(<a href="references.html#ref-poole2022" role="doc-biblioref">Poole 2022</a>)</span>.</p>
<p>His (very firmly-held) position is that there is no reforming null hypothesis significance testing. Instead, our focus should be on estimation. Where significance testing is of some utility, frame the results in terms of substantive results and estimation of effect size, instead of statistical significance.</p>
<p>I am of the view that hypothesis testing is generally a sub-optimal approach when trying to better understand phenomenon using data. Hypothesis testing cannot tell us what we really need to know, and our confidence in the results of even seemingly well-constructed hypothesis tests is pretty shaky by now, so where possible I would generally focus on trying to estimate the effects.</p>
<!-- I concede that healthcare, particularly a  clinical setting, is a domain where there is real value to testing the difference between groups. It's also valuable to be able to dichotomise a p-value in some settings, and frame a difference in terms of our confidence that it has not occurred by chance. For example, comparing the effect of a drug or an intervention of some sort on patient outcomes. I would still argue that, in this case, estimation is still the appropriate way to go more often than not (possibly even always, but I'm unsure how far I'm willing to go in this regard), but knowing that hypothesis testing is not going away, I will try to equip readers with the tools to carry out robust hypothesis tests. -->
<p>This doesn’t necessarily alter the statistical methods we will use (though more on this at the end of this chapter), but it does require our adjusting how we approach these methods and what we look to get out of them.</p>
<p>Build statistical models that are more ambitious than simply attempting to identify the existence of an effect. We should care enough to try and measure things that matter more than that. We should seek to know what that effect is, and we should have the confidence in our ability to care about things that are, at a minimum, doing something. <span class="citation" data-cites="gelman2020">Gelman, Hill, and Vehtari (<a href="references.html#ref-gelman2020" role="doc-biblioref">2020</a>)</span> argue that we are generally capable of being interested in issues where effects exist, and that the presence an effect is therefore not entirely interesting, in and of itself. Therefore, we should concern ourselves with the things that do matter, like the size of the effect, not the existence of the effect itself.</p>
<p>It is rare that we should only care that the effect exists. Generally speaking, this should be a prerequisite to the more important question of what the magnitude and direction of that effect is. Even where the knowledge of the existence of an effect is sufficient, it is hard for me to imagine a situation where knowing the magnitude and direction of the effect wouldn’t be useful, and wouldn’t allow us to estimate our confidence in that effect more effectively.</p>
</section><section id="embrace-uncertainty" class="level4" data-number="6.3.2.2"><h4 data-number="6.3.2.2" class="anchored" data-anchor-id="embrace-uncertainty">
<span class="header-section-number">6.3.2.2</span> Embrace Uncertainty</h4>
<p>When we move away from testing null hypotheses and focus instead on the estimation of effect sizes, we go from testing for the existence of an effect to estimating the magnitude and the direction of the effect. However, a key part of this that is missing is the precision with which we are able to estimate the effect. It’s important to remember, in any statistical modelling, that we are estimating quantities, and therefore any point estimate is just our best effort at quantifying an unknown population parameter. The point estimate is probably wrong! It is important that we acknowledge the uncertainty in our estimations and account for them in the way we present model outputs.</p>
<p>However, the embrace of uncertainty is not limited to our uncertainty in our estimates. It is a wider issue. We have to accept that every part of the process of estimating meaningful quantities is done with a degree of uncertainty, and as such the way we think about statistical modelling and the way we present our results should account for the existence of variance. Uncertainty exists everywhere in statistical analysis and inference <span class="citation" data-cites="wasserstein2019">(<a href="references.html#ref-wasserstein2019" role="doc-biblioref">Wasserstein, Schirm, and Lazar 2019</a>)</span>.</p>
<p><span class="citation" data-cites="wasserstein2019">Wasserstein, Schirm, and Lazar (<a href="references.html#ref-wasserstein2019" role="doc-biblioref">2019</a>)</span> describe the use of “significance tests and dichotomized p-values” as an attempt by some practitioners to avoid dealing with uncertainty, by escaping to a more simplistic world where results are either statistically significant or not.</p>
<p><span class="citation" data-cites="greenland2016">Greenland et al. (<a href="references.html#ref-greenland2016" role="doc-biblioref">2016</a>)</span> argue that the goal of a statistical analysis is to provide an evaluation of our certainty (or uncertainty) of an effect size. Embracing uncertainty means recognising that it is fundamental to every aspect of what we do, and the way we talk about our work, how we present it, and the conclusions we draw from it, must accept this fact.</p>
<p>In order to achieve this we have to accept that findings are more uncertain than is often acknowledged.</p>
<p>Our embrace of uncertainty should help us to seek out better methods, apply the necessary amount of care and critical thinking to our work, and draw inferences with the appropriate amount of confidence.</p>
<p>One way of acknowledging and working with this uncertainty is the use of confidence intervals when estimating effect sizes. Confidence intervals estimate a range of values that would be compatible with the data, given all of the statistical model’s assumptions are met. While confidence intervals are ultimately estimated from the p-value, and the typical 95% confidence interval corresponds to the p &gt; .05 threshold that I have warned against, they are useful because they frame results in terms of effect sizes, and they incorporate uncertainty in our estimates.</p>
<p>Further, confidence intervals give us some sense of the precision with which we are able to estimate effect size.</p>
<p>Consider using confidence intervals - though they won’t fix issues with testing, they are useful for testing the precision of the estimation process when estimating meaningful quantities.</p>
<p><span class="citation" data-cites="gelman2016">Gelman (<a href="references.html#ref-gelman2016" role="doc-biblioref">2016</a>)</span> states that “the solution is not to reform p-values or to replace them with some other statistical summary or threshold, but rather to move toward a greater acceptance of uncertainty and embracing of variation”.</p>

<!-- "If researchers have been trained with the expectation that they will get statistical significance if they work hard and play by the rules... it is no surprise that researchers will routinely satisfy this criterion, and publish, and publish, and publish, even in the absence of any real effects, or in the context of effects that are so variable as to be undetectable in the studies that are being conducted." [@gelman2016] -->
<!-- "Much statistical teaching and practice has developed a strong (and unhealthy) focus on the idea that the main aim of a study should be to test null hypotheses. In fact most descriptions of statistical testing focus only on testing null hypotheses, and the entire topic has been called 'Null Hypothesis Significance Testing' (NHST). This exclusive focus on null hypotheses contributes to misunderstanding of tests. Adding to the misunderstanding is that many authors (including R.A. Fisher) use 'null hypothesis' to refer to any test hypothesis, even though this usage is at odds with other authors and with ordinary English definitions of 'null' — as are statistical usages of 'significance' and 'confidence'." [@greenland2016, pp. 339] -->
<p>Ultimately, using confidence intervals with a hypothesis test doesn’t get you much further than p-values. So embracing uncertainty in the results of a hypothesis test isn’t as simple as estimating intervals instead of point values. But acknowledging the uncertainty in our estimation of an effect size frames our statistical modelling approach in more robust terms.</p>
</section></section></section><section id="building-statistical-tests" class="level2" data-number="6.4"><h2 data-number="6.4" class="anchored" data-anchor-id="building-statistical-tests">
<span class="header-section-number">6.4</span> Building Statistical Tests</h2>
<p>A generalised framework for hypothesis testing, that discards of NHST’s problematic baggage (instead following a Fisherian approach <span class="citation" data-cites="fisher1956">(<a href="references.html#ref-fisher1956" role="doc-biblioref">Fisher 1956</a>)</span>), would take the following steps:</p>
<ol type="1">
<li>Specify the test hypothesis (<span class="math inline">\(H_0\)</span>) that assumes some effect size against which the observed effect size will be compared - this will often be a <!-- NHST also specifies an alternative hypothesis ($H_1$) and significance level ($\alpha$)). -->
</li>
<li>Generate the test distribution, defined by the data being analysed and the test being carried out, which represents our expectation of what we would observe if the statistical model’s assumptions, which include the test hypothesis, are all true.</li>
<li>Compute the test statistic, which quantifies how extreme the observed data is, given the test distribution.</li>
<li>Compute the p-value, representing the probability of observing a test statistic as large or larger than the observed test statistic if all of the assumptions of the statistical model, including the test hypothesis, are true.</li>
<li>
</li></ol>
<p>The intuition behind hypothesis testing may not be entirely clear from this. The important takeaway is that our test statistic is our measure of the observed/sample data, our test/null distribution is our measure of what we would expect to observe if the test/null hypothesis, and all other model assumptions, are true, and our statistical test is simply quantifying how compatible our observed data would be with the generated distribution.</p>
<p>While there are many different statistical tests that are designed to test different data distributions, using different assumptions, the general framework is the same. Below are some examples of statistical tests that are commonly used.</p>
<section id="t-tests" class="level3" data-number="6.4.1"><h3 data-number="6.4.1" class="anchored" data-anchor-id="t-tests">
<span class="header-section-number">6.4.1</span> T-Tests</h3>
<p>The general idea of a t-test is to calculate the statistical significance of the difference between two groups. What the groups represent depends on the type of t-test being carried out, whether it be comparing a single group of observed data against a null distribution that assumes the data was generated by chance, or comparing the difference between two observed groups against a null distribution that assumes the difference is zero.</p>
<p>There are several broad groups of t-tests:</p>
<ul>
<li>One-sample t-test - comparing the sample mean of a single group against a “known mean”, generally testing whether a sample is likely to be generated by chance.</li>
<li>Paired t-test - comparing means from the same group measured multiple times, like how someone responds to a survey at different points in time.</li>
<li>Two samples t-test - comparing the means of two groups, such as measuring the difference in blood glucose levels of two different groups.</li>
</ul>
<p>There are several variations within these groups, for example a paired t-test generally assumes equal variance between the two groups, but this is often not true, so an unequal variance t-test can be used.</p>
<p>Finally, when deciding on the nature of a t-test, you must also decide if the test should be one-tailed or two-tailed. A one-tailed t-test is used to test a hypothesis that includes a directional component (such as <span class="math inline">\(x &gt; y\)</span>), while a two-tailed t-test is just testing whether there is a difference between two groups. A one-tailed t-test is appropriate when you believe the difference between two groups should be positive or negative, but if the only belief is that the groups are different, a two-tailed t-test is appropriate.</p>
<p>A two-tailed t-test compares whether the sample mean(s) is different, whether larger or smaller, while a one-tailed t-test assumes the direction of the difference is known. For example, if it is known that Group A is either the same or bigger than Group B (or that Group A being smaller is not of interest), then a one-tailed t-test would be appropriate.</p>
<p>I will simulate data from real-world examples to demonstrate one-sample, paired, and two-sample t-tests, however, these examples are not exhaustive, and there are many variations on t-test implementations.<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a></p>
<section id="one-sample-t-test" class="level4" data-number="6.4.1.1"><h4 data-number="6.4.1.1" class="anchored" data-anchor-id="one-sample-t-test">
<span class="header-section-number">6.4.1.1</span> One-Sample T-Test</h4>
<p>We can carry out a one-sample t-test using IQ scores as our example, because there is plenty of data out there about IQ scores that we can base our simulations on. The average IQ score is said to be around 100, and scores are normally distributed with a standard deviation of 15, meaning that the majority of people have an IQ in the range of 85-115.</p>
<p>In a one-sample t-test we are interested in testing a sample mean against an “expected” mean. For example, perhaps we have a group of individuals that are viewed as “high achievers”, and we want to use IQ scores to test whether this group is meaningfully different to the rest of the population (despite being aware that IQ is not a particularly good test of either an individual’s intelligence or their potential).</p>
<p>A one-sample t-test would allow us to do this because we are able to test the mean IQ score for our high achievers against the expected mean value if there was no real difference between them and the population, which would just be the mean IQ score in the population (100).</p>
<p>Lets first start by simulating our high achievers’ IQ scores, assuming that their mean score is 105 (perhaps some of the group studied IQ tests extensively and are now able to ace the test), with a standard deviation of 15.</p>
<div class="cell" data-hash="hypothesis_testing_r_cache/html/unnamed-chunk-2_a99cd1a592a97a22fddd23e461df42b2">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># label: simulate-high-achievers</span></span>
<span></span>
<span><span class="va">high_achievers</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://tibble.tidyverse.org/reference/tibble.html">tibble</a></span><span class="op">(</span>score <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="fl">10</span>, mean <span class="op">=</span> <span class="fl">105</span>, sd <span class="op">=</span> <span class="fl">15</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We can take a look at the sample data we have simulated, to see how close it is to the true mean and standard deviation (because we are simulating the data it won’t be a perfect match).</p>
<div class="cell" data-hash="hypothesis_testing_r_cache/html/summarise-sample_58288acbcb17574854efcab0e21e120c">
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># compute summary statistics for our sample</span></span>
<span><span class="va">high_achievers</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise</a></span><span class="op">(</span></span>
<span>    mean <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">score</span><span class="op">)</span>,</span>
<span>    std_dev <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">score</span><span class="op">)</span></span>
<span>    <span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
   mean std_dev
  &lt;dbl&gt;   &lt;dbl&gt;
1  106.    14.3</code></pre>
</div>
</div>
<p>And we can visualise the data to get a better sense of what the group looks like.</p>
<div class="cell" data-hash="hypothesis_testing_r_cache/html/visualise-sample_0a6362811cf87212c5358d2a106b3155">
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">high_achievers</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span><span class="va">score</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_histogram.html">geom_histogram</a></span><span class="op">(</span>binwidth <span class="op">=</span> <span class="fl">5</span>, colour <span class="op">=</span> <span class="st">"#FFFFFF"</span>, linewidth <span class="op">=</span> <span class="fl">1</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_abline.html">geom_hline</a></span><span class="op">(</span>yintercept <span class="op">=</span> <span class="fl">0</span>, colour <span class="op">=</span> <span class="st">"#333333"</span>, linewidth <span class="op">=</span> <span class="fl">1</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_continuous.html">scale_x_continuous</a></span><span class="op">(</span>breaks <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span><span class="fl">80</span>, <span class="fl">130</span>, <span class="fl">5</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"IQ Score"</span>, y <span class="op">=</span> <span class="cn">NULL</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="hypothesis_testing_r_files/figure-html/visualise-sample-1.png" class="img-fluid" width="960"></p>
</div>
</div>
<p>It is not clear what the underlying distribution of our sample data is here. We already know that the data was drawn from a normal distribution, but if we did not, we would need more observations to confirm this.</p>
<div class="cell" data-hash="hypothesis_testing_r_cache/html/one-sample-test_b84fd70d91174b22e6c5dab4b1f45f5d">
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://infer.tidymodels.org/reference/t_test.html">t_test</a></span><span class="op">(</span><span class="va">high_achievers</span>, response <span class="op">=</span> <span class="va">score</span>, mu <span class="op">=</span> <span class="fl">100</span>, alternative <span class="op">=</span> <span class="st">"greater"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 7
  statistic  t_df p_value alternative estimate lower_ci upper_ci
      &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt; &lt;chr&gt;          &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
1      1.35     9   0.105 greater         106.     97.8      Inf</code></pre>
</div>
</div>
<p>The p-value of our one-sample t-test is 0.105. This means that we would expect to observe a sample mean at least as extreme as our observed mean (106), if the null that there is no difference between the high achiever group’s mean IQ score and the population mean IQ score is true, a little more than 10% of the time, or 1 in 10 times. That’s quite high, so I wouldn’t be confident that we are observing a meaningful difference.</p>
<p>However, we know that there is a meaningful difference between our high achievers and the population, because we specified a difference when we simulated our sample data. If we were to conclude that the results we observe in our t-test do not lend any support to our hypothesis that the high achievers are better at IQ tests than the average person<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a>, this would be a false negative (or sometimes unhelpfully referred to as a Type 1 Error).</p>
<p>If we increase our sample size, maybe we will have more luck!</p>
<div class="cell" data-hash="hypothesis_testing_r_cache/html/increase-sample-size_ee972975443be3e7c8f39a4da0410f01">
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">larger_sample</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://tibble.tidyverse.org/reference/tibble.html">tibble</a></span><span class="op">(</span>score <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="fl">30</span>, mean <span class="op">=</span> <span class="fl">105</span>, sd <span class="op">=</span> <span class="fl">15</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://infer.tidymodels.org/reference/t_test.html">t_test</a></span><span class="op">(</span><span class="va">larger_sample</span>, response <span class="op">=</span> <span class="va">score</span>, mu <span class="op">=</span> <span class="fl">100</span>, alternative <span class="op">=</span> <span class="st">"greater"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 7
  statistic  t_df p_value alternative estimate lower_ci upper_ci
      &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt; &lt;chr&gt;          &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
1      2.26    29  0.0159 greater         106.     101.      Inf</code></pre>
</div>
</div>
<p>Increasing the sample size from 10 to 30 has decreased the probability of observing a test statistic at least as extreme as our sample mean if our data was generated by chance (and the assumptions of our statistical model are all met) from around 10% to just over 1.5%. That seems a lot more reasonable, and at this point I’d be more comfortable concluding that the high achiever’s IQ scores are meaningfully different to the average score in the population.</p>
<p>Of course, our p-value doesn’t tell us anything about the substantive importance of the difference in IQ scores. We might be willing to conclude that there <strong>is</strong> a difference, but does it matter? Well, the answer is no because it’s IQ scores and IQ scores don’t matter.</p>
<p>But what if, for some truly baffling reason, we had reason to believe IQ scores are not nonsense? In that case, how do we know if the difference between the mean value in the high achievers group and the population is large enough to be of scientific and substantive relevance? This is not a question that significance tests can answer, and is instead something that our domain expertise should answer.</p>
</section><section id="paired-t-test" class="level4" data-number="6.4.1.2"><h4 data-number="6.4.1.2" class="anchored" data-anchor-id="paired-t-test">
<span class="header-section-number">6.4.1.2</span> Paired T-Test</h4>
<p>When respondents in surveys are asked to self-report certain details about themselves, this can invite bias. Take, for example, the difference in <a href="https://digital.nhs.uk/data-and-information/areas-of-interest/public-health/health-survey-for-england-predicting-height-weight-and-body-mass-index-from-self-reported-data/differences-between-self-reported-and-interviewer-measured-height-weight-and-bmi-using-hse-2011-2016-data">self-reported and interviewer-measured height among men in the UK</a>. Although there are many proud short kings out there that will confidently declare their height, safe in the knowledge that good things come in small packages, there are plenty of men that wish they were a little bit taller (someone should write a song about that), and for whom a self-reported survey is an opportunity to dream big (literally). Any time that respondents are given the opportunity to report details about themselves that have any social baggage attached, there is a possibility that the responses will be subject to social desirability bias.</p>
<p>In the case of self-reported and measured male heights, the differences are not particularly large in absolute terms. It’s very possible that the difference is actually a product of some random variation, or measurement error. We can test this!</p>
<p>Using the mean values for reported and measured heights in 2016, calculating the standard deviation from the reported standard error<a href="#fn7" class="footnote-ref" id="fnref7" role="doc-noteref"><sup>7</sup></a>, and calculating the correlation between the two variables using the value for each variable from 2011-2016<a href="#fn8" class="footnote-ref" id="fnref8" role="doc-noteref"><sup>8</sup></a>, we can simulate our sample data.</p>
<div class="cell" data-hash="hypothesis_testing_r_cache/html/simulate-male-heights_621808a01147204e6e88b5166e0259f7">
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">short_kings</span> <span class="op">&lt;-</span></span>
<span>  <span class="fu">faux</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/faux/man/rnorm_multi.html">rnorm_multi</a></span><span class="op">(</span></span>
<span>    n <span class="op">=</span> <span class="fl">100</span>,</span>
<span>    vars <span class="op">=</span> <span class="fl">2</span>,</span>
<span>    mu <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">177.23</span>, <span class="fl">175.71</span><span class="op">)</span>,</span>
<span>    sd <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">9.02</span>, <span class="fl">8.99</span><span class="op">)</span>,</span>
<span>    r <span class="op">=</span> <span class="fl">0.83</span>,</span>
<span>    varnames <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"self_reported_height"</span>, <span class="st">"measured_height"</span><span class="op">)</span></span>
<span>  <span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>height_diff <span class="op">=</span> <span class="va">self_reported_height</span> <span class="op">-</span> <span class="va">measured_height</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We have simulated the self-reported and measured height for 100 men, given the mean, standard deviation, and correlation as detailed in Table 1 of the above analysis<a href="#fn9" class="footnote-ref" id="fnref9" role="doc-noteref"><sup>9</sup></a>. Using these two simulated variables, we are then able to calculate the difference between the two, and carry out a simple one-sample t-test that compares that difference against a null hypothesis with mean zero.</p>
<div class="cell" data-hash="hypothesis_testing_r_cache/html/male-heights-test_c615758d6e7fb55b51bee74e33306ebf">
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://infer.tidymodels.org/reference/t_test.html">t_test</a></span><span class="op">(</span><span class="va">short_kings</span>, response <span class="op">=</span> <span class="va">height_diff</span>, mu <span class="op">=</span> <span class="fl">0</span>, direction <span class="op">=</span> <span class="st">"greater"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 7
  statistic  t_df p_value alternative estimate lower_ci upper_ci
      &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt; &lt;chr&gt;          &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
1      2.75    99 0.00719 two.sided       1.40    0.387     2.40</code></pre>
</div>
</div>
<p>The difference between the self-reported and measured heights has a p-value of 0.00719, suggesting there is a 0.7% probability of observing a t-statistic at least as extreme as we observe here, if the data was generated by chance and if the assumptions of our statistical model are valid.</p>
<p>More importantly, we observe an estimated difference between self-reported height and measured height of 1.4cm, with about 1cm difference from our estimate and our lower and upper confidence intervals, which suggests that the difference between self-reported height for men is larger than their measured heights. However, is 1.4cm significant enough to really care? I mean, none of this is important enough (or valid enough) to really care, but if we suspend disbelief for a moment, is a 1.4cm difference substantively meaningful? I’ll leave that up to you to decide.</p>
</section><section id="two-samples-t-test" class="level4" data-number="6.4.1.3"><h4 data-number="6.4.1.3" class="anchored" data-anchor-id="two-samples-t-test">
<span class="header-section-number">6.4.1.3</span> Two Samples T-Test</h4>
<p>So we’ve established a very real, totally scientific over-reporting of male height across the UK, and some clever, entrepreneurial, and not at all exploitative pharmaceutical company has had the good sense to develop a medication that gives you an extra couple of inches in height.</p>
<p>In order to prove that it works it needs to go through testing (because we are particularly reckless, we don’t really care if it is safe in this example). An experiment is designed, with a treatment and control group that is representative of the wider male population, and the wonder drug is given to the treatment group.</p>
<p>We can compare the change in height for the two groups in the 6 months after the treatment group have taken the medication, hypothesising that the drug has had a positive effect on the treatment group, helping them grow by a whopping 1.5cm! This is compared against the average increase in height for the control group that is approximately zero, with a very small standard deviation. A two-sample t-test can help us shed some light on whether we can be confident that this difference did not occur by chance.</p>
<p>We simulate our treatment and control groups, with 20 observations in each, with the treatment group having a mean growth of 3cm and standard deviation of 3cm, and the control group having a mean growth of 0cm and a standard deviation of 0.5cm.</p>
<div class="cell" data-hash="hypothesis_testing_r_cache/html/simulate-height-experiment_e65cc454561bfc947a6b45342b6bb6ce">
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">growers</span> <span class="op">&lt;-</span></span>
<span>  <span class="fu"><a href="https://tibble.tidyverse.org/reference/tibble.html">tibble</a></span><span class="op">(</span></span>
<span>    group <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"treatment"</span>, <span class="st">"control"</span><span class="op">)</span>, times <span class="op">=</span> <span class="fl">20</span><span class="op">)</span>,</span>
<span>    growth <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="fl">40</span>, mean <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">3</span>, <span class="fl">0</span><span class="op">)</span>, sd <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">3</span>, <span class="fl">.5</span><span class="op">)</span><span class="op">)</span></span>
<span>  <span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Having simulated our treatment and control groups, we can compute a t-test to see if there is a difference in how much each group has grown, on average.</p>
<div class="cell" data-hash="hypothesis_testing_r_cache/html/height-experiment_38bcc02e4e9161e24d80ac255af1b857">
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://infer.tidymodels.org/reference/t_test.html">t_test</a></span><span class="op">(</span><span class="va">growers</span>, formula <span class="op">=</span> <span class="va">growth</span> <span class="op">~</span> <span class="va">group</span>,</span>
<span>       order <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"treatment"</span>, <span class="st">"control"</span><span class="op">)</span>,</span>
<span>       alternative <span class="op">=</span> <span class="st">"greater"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 7
  statistic  t_df     p_value alternative estimate lower_ci upper_ci
      &lt;dbl&gt; &lt;dbl&gt;       &lt;dbl&gt; &lt;chr&gt;          &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
1      6.84  20.6 0.000000511 greater         3.94     2.95      Inf</code></pre>
</div>
</div>
<p>The probability that we would observe a test statistic as large or larger than observed here is very, very small, and the results of the t-test estimate that the difference between the two groups is a little bit less than 4cm, with a lower confidence interval of just under 3cm, suggesting that this medication is having a positive difference on height in the treatment group!</p>
</section></section><section id="chi-squared-tests" class="level3" data-number="6.4.2"><h3 data-number="6.4.2" class="anchored" data-anchor-id="chi-squared-tests">
<span class="header-section-number">6.4.2</span> Chi-Squared Tests</h3>
<p>Although there are many ways that you may encounter chi-squared (<span class="math inline">\(\chi^2\)</span>) tests, the two most common are tests of independence and a goodness of fit tests. The chi-squared test of independence is a test of the association between two categorical variables, meaning whether the variables are related or not. It is testing whether they vary independently of each other. A chi-squared goodness of fit test is used to examine how well a theoretical distribution fits the distribution of a categorical variable. We will focus on the test of independence here, because I think this is the most common use case.</p>
<p>A common use-case for chi-squared tests of independence is survey data, where individuals from different groups respond to a survey question that offers a finite number of discrete answers, like a scale from good to bad. A good example of categorical variables used in survey data is the impact of male baldness on 46 year old men, carried out by <span class="citation" data-cites="sinikumpu2021">Sinikumpu et al. (<a href="references.html#ref-sinikumpu2021" role="doc-biblioref">2021</a>)</span>. In this survey they grouped men by levels of baldness, and asked them various questions about their lives, from education to sex-life, to consider the impact that being bald has on men’s lives and well-being.</p>
<p>We will use the education question as the basis for simulating the data for our chi-squared test. The survey splits education-level in to three groups - basic, secondary, and tertiary - while I have simplified the question by turning the levels of baldness into a binary categorical variable.</p>
<div class="cell" data-hash="hypothesis_testing_r_cache/html/simulate-survey_36958ba85fd11f1ca0f41e73ab51a27f">
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">not_bald</span> <span class="op">&lt;-</span></span>
<span>  <span class="fu"><a href="https://tibble.tidyverse.org/reference/tibble.html">tibble</a></span><span class="op">(</span></span>
<span>    hair_status <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="st">"Not Bald"</span>, times <span class="op">=</span> <span class="fl">300</span><span class="op">)</span>,</span>
<span>    education <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sample.html">sample</a></span><span class="op">(</span></span>
<span>      <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Basic"</span>, <span class="st">"Secondary"</span>, <span class="st">"Tertiary"</span><span class="op">)</span>,</span>
<span>      size <span class="op">=</span> <span class="fl">300</span>, replace <span class="op">=</span> <span class="cn">TRUE</span>, </span>
<span>      prob <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0.039</span>, <span class="fl">0.594</span>, <span class="fl">0.367</span><span class="op">)</span><span class="op">)</span></span>
<span>  <span class="op">)</span></span>
<span></span>
<span><span class="va">bald</span> <span class="op">&lt;-</span></span>
<span>  <span class="fu"><a href="https://tibble.tidyverse.org/reference/tibble.html">tibble</a></span><span class="op">(</span></span>
<span>    hair_status <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="st">"Bald"</span>, times <span class="op">=</span> <span class="fl">600</span><span class="op">)</span>,</span>
<span>    education <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sample.html">sample</a></span><span class="op">(</span></span>
<span>      <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Basic"</span>, <span class="st">"Secondary"</span>, <span class="st">"Tertiary"</span><span class="op">)</span>,</span>
<span>      size <span class="op">=</span> <span class="fl">600</span>, replace <span class="op">=</span> <span class="cn">TRUE</span>, </span>
<span>      prob <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0.03</span>, <span class="fl">0.603</span>, <span class="fl">0.367</span><span class="op">)</span><span class="op">)</span></span>
<span>    <span class="op">)</span></span>
<span></span>
<span><span class="va">baldness_survey</span> <span class="op">&lt;-</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/cbind.html">rbind</a></span><span class="op">(</span><span class="va">not_bald</span>, <span class="va">bald</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We have simulated each of the different baldness categories individually, before combining them into a single dataset. I think there should be a more concise way of doing this, but I haven’t wrapped my head round how I should do that yet.</p>
<p>We can visualise the difference between the three education-levels in terms of proportion of baldness, to see if there is an obvious difference.</p>
<div class="cell" data-hash="hypothesis_testing_r_cache/html/visualise-survey_ca47b423638d176bd085a2e1333314b6">
<div class="sourceCode" id="cb17"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">baldness_survey</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span><span class="va">education</span>, fill <span class="op">=</span> <span class="va">hair_status</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_bar.html">geom_bar</a></span><span class="op">(</span>position <span class="op">=</span> <span class="st">"fill"</span>, colour <span class="op">=</span> <span class="st">"#FFFFFF"</span>, linewidth <span class="op">=</span> <span class="fl">1</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_abline.html">geom_hline</a></span><span class="op">(</span>yintercept <span class="op">=</span> <span class="fl">0</span>, colour <span class="op">=</span> <span class="st">"#333333"</span>, linewidth <span class="op">=</span> <span class="fl">1</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">scwplot</span><span class="fu">::</span><span class="fu"><a href="https://nhs-south-central-and-west.github.io/scwplot/reference/scale_qualitative.html">scale_fill_qualitative</a></span><span class="op">(</span><span class="st">"nhs"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Education Level"</span>, y <span class="op">=</span> <span class="st">"Proportion"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="hypothesis_testing_r_files/figure-html/visualise-survey-1.png" class="img-fluid" width="960"></p>
</div>
</div>
<p>There’s a small difference between people with a basic education, but for secondary and tertiary education it seems to be pretty evenly split. Our chi-squared test can test this empirically.</p>
<div class="cell" data-hash="hypothesis_testing_r_cache/html/chi-sq-test_4acd4f61f064eff4c698b7f89c189169">
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://infer.tidymodels.org/reference/chisq_test.html">chisq_test</a></span><span class="op">(</span><span class="va">baldness_survey</span>, <span class="va">education</span> <span class="op">~</span> <span class="va">hair_status</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  statistic chisq_df p_value
      &lt;dbl&gt;    &lt;int&gt;   &lt;dbl&gt;
1      3.38        2   0.184</code></pre>
</div>
</div>
<p>So our p-value tells us that we should expect to observe data at least extreme as our simulated survey data a little less than 20% of the time, if the null hypothesis that there is no difference in education levels across levels of hair loss is true. This is a smaller p-value than <span class="citation" data-cites="sinikumpu2021">Sinikumpu et al. (<a href="references.html#ref-sinikumpu2021" role="doc-biblioref">2021</a>)</span> observe (0.299), but that will be a consequence of the fact we are simulating the data using probabilistic samples, not replicating their results exactly.</p>
<p>If we were to fudge the numbers a little bit, so as to artificially increase the difference in education levels based on the amount of hair a 46 year old man has, what would our results look like?</p>
<div class="cell" data-hash="hypothesis_testing_r_cache/html/add-effect_71de523dadf620df90a2ab47d23eff47">
<div class="sourceCode" id="cb20"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">not_bald</span> <span class="op">&lt;-</span></span>
<span>  <span class="fu"><a href="https://tibble.tidyverse.org/reference/tibble.html">tibble</a></span><span class="op">(</span></span>
<span>    hair_status <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="st">"Not Bald"</span>, times <span class="op">=</span> <span class="fl">300</span><span class="op">)</span>,</span>
<span>    education <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sample.html">sample</a></span><span class="op">(</span></span>
<span>      <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Basic"</span>, <span class="st">"Secondary"</span>, <span class="st">"Tertiary"</span><span class="op">)</span>,</span>
<span>      size <span class="op">=</span> <span class="fl">300</span>, replace <span class="op">=</span> <span class="cn">TRUE</span>, </span>
<span>      prob <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0.15</span>, <span class="fl">0.55</span>, <span class="fl">0.3</span><span class="op">)</span><span class="op">)</span></span>
<span>  <span class="op">)</span></span>
<span></span>
<span><span class="va">bald</span> <span class="op">&lt;-</span></span>
<span>  <span class="fu"><a href="https://tibble.tidyverse.org/reference/tibble.html">tibble</a></span><span class="op">(</span></span>
<span>    hair_status <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="st">"Bald"</span>, times <span class="op">=</span> <span class="fl">600</span><span class="op">)</span>,</span>
<span>    education <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sample.html">sample</a></span><span class="op">(</span></span>
<span>      <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Basic"</span>, <span class="st">"Secondary"</span>, <span class="st">"Tertiary"</span><span class="op">)</span>,</span>
<span>      size <span class="op">=</span> <span class="fl">600</span>, replace <span class="op">=</span> <span class="cn">TRUE</span>, </span>
<span>      prob <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0.05</span>, <span class="fl">0.6</span>, <span class="fl">0.35</span><span class="op">)</span><span class="op">)</span></span>
<span>    <span class="op">)</span></span>
<span></span>
<span><span class="va">baldness_survey_with_effect</span> <span class="op">&lt;-</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/cbind.html">rbind</a></span><span class="op">(</span><span class="va">not_bald</span>, <span class="va">bald</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://infer.tidymodels.org/reference/chisq_test.html">chisq_test</a></span><span class="op">(</span><span class="va">baldness_survey_with_effect</span>, <span class="va">education</span> <span class="op">~</span> <span class="va">hair_status</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  statistic chisq_df     p_value
      &lt;dbl&gt;    &lt;int&gt;       &lt;dbl&gt;
1      31.6        2 0.000000134</code></pre>
</div>
</div>
<p>Having increased the number of respondents with a basic education (and in turn decreasing those with secondary and tertiary educations) for the not bald group, our chi-squared test results suggest the data we observe is much more extreme. The p-value for this test is extremely small, but that’s not totally surprising. We did fake our data, after all.</p>
</section><section id="simulation-based-statistical-tests" class="level3" data-number="6.4.3"><h3 data-number="6.4.3" class="anchored" data-anchor-id="simulation-based-statistical-tests">
<span class="header-section-number">6.4.3</span> Simulation-Based Statistical Tests</h3>
<p>One of the reasons I always struggled with hypothesis testing when first learning about them is the seemingly endless variations of tests, each suited to a slightly different data distribution or context. While you could take on the arduous task of learning as many different tests as possible, it is probably (definitely) better to think in terms of the framework for carrying out a hypothesis test that was detailed earlier, and understanding all tests as generalisations of this framework.</p>
<p>This was an idea pitched by the computer scientist Allen Downey, when he wrote that “there is only one test”. He’s right. This framework for understanding all hypothesis tests as variations on the same basic method uses simulated data from permutation or bootstrapping methods to generate the null distribution against which observed data can be evaluated.</p>
<p>When classical significance testing methods were developed, simulation wasn’t possible, due to the absence of computational power. Now that we have high-powered machines that will do everything for us, we don’t have to worry about this so much, which makes simulation much more viable.</p>
<p>Downey visualises how this simulation-based workflow for hypothesis testing works using the following diagram:</p>
<p><img src="figures/hypothesis_testing.png" class="img-fluid"></p>
<p>The <a href="https://github.com/tidymodels/infer">infer</a> workflow for carrying out simulation-based hypothesis tests is designed based on the same principles (<code><a href="https://infer.tidymodels.org/reference/specify.html">specify()</a></code>, <code><a href="https://infer.tidymodels.org/reference/hypothesize.html">hypothesize()</a></code>, <code><a href="https://infer.tidymodels.org/reference/generate.html">generate()</a></code>, <code><a href="https://infer.tidymodels.org/reference/calculate.html">calculate()</a></code>, &amp; <code><a href="https://infer.tidymodels.org/reference/visualize.html">visualize()</a></code>). This all-in-one process for hypothesis testing is a little more involved than the humble t-test, and the code for computing hypothesis tests using this approach is definitely more verbose. However, the power that this process gives you is that you can easily carry out any hypothesis test once you’ve learned Downey’s framework, and the consistency of the <a href="https://github.com/tidymodels/infer">infer</a> workflow makes it easier to learn how to do this. The <a href="https://github.com/tidymodels/infer">infer</a> documentation also provides a <a href="https://infer.tidymodels.org/articles/observed_stat_examples.html">pretty exhaustive list</a> of how to compute hypothesis tests under a variety of conditions.</p>
<p>We can see <a href="https://github.com/tidymodels/infer">infer</a> in action by recalculating our IQ scores t-test that we carried out earlier on. Here is what that looks like using simulation-based methods.</p>
<div class="cell" data-hash="hypothesis_testing_r_cache/html/high-achievers-sim-test_5863be5086c2bc6d44f3d4d586878b35">
<div class="sourceCode" id="cb22"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># compute test statistic</span></span>
<span><span class="va">test_statistic</span> <span class="op">&lt;-</span> </span>
<span>  <span class="va">larger_sample</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://infer.tidymodels.org/reference/specify.html">specify</a></span><span class="op">(</span>response <span class="op">=</span> <span class="va">score</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://infer.tidymodels.org/reference/calculate.html">calculate</a></span><span class="op">(</span>stat <span class="op">=</span> <span class="st">"mean"</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># generate null distribution</span></span>
<span><span class="va">null_distribution</span> <span class="op">&lt;-</span> </span>
<span>  <span class="va">larger_sample</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://infer.tidymodels.org/reference/specify.html">specify</a></span><span class="op">(</span>response <span class="op">=</span> <span class="va">score</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://infer.tidymodels.org/reference/hypothesize.html">hypothesize</a></span><span class="op">(</span>null <span class="op">=</span> <span class="st">"point"</span>, mu <span class="op">=</span> <span class="fl">100</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://infer.tidymodels.org/reference/generate.html">generate</a></span><span class="op">(</span>reps <span class="op">=</span> <span class="fl">1000</span>, type <span class="op">=</span> <span class="st">"bootstrap"</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://infer.tidymodels.org/reference/calculate.html">calculate</a></span><span class="op">(</span>stat <span class="op">=</span> <span class="st">"mean"</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># calculate the p-value of observing a test statistic at least as extreme as </span></span>
<span><span class="co"># our observed statistic if the data was generated by chance</span></span>
<span><span class="va">p_value</span> <span class="op">&lt;-</span> </span>
<span>  <span class="va">null_distribution</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://infer.tidymodels.org/reference/get_p_value.html">get_p_value</a></span><span class="op">(</span>obs_stat <span class="op">=</span> <span class="va">test_statistic</span>, direction <span class="op">=</span> <span class="st">"greater"</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># visualise the test statistic against the null</span></span>
<span><span class="va">null_distribution</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://infer.tidymodels.org/reference/visualize.html">visualize</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://infer.tidymodels.org/reference/shade_p_value.html">shade_p_value</a></span><span class="op">(</span><span class="va">test_statistic</span>, direction <span class="op">=</span> <span class="cn">NULL</span>, color <span class="op">=</span> <span class="st">"#00A499"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_abline.html">geom_hline</a></span><span class="op">(</span>yintercept <span class="op">=</span> <span class="fl">0</span>, colour <span class="op">=</span> <span class="st">"#333333"</span>, linewidth <span class="op">=</span> <span class="fl">1</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/annotate.html">annotate</a></span><span class="op">(</span></span>
<span>    <span class="st">"text"</span>, x <span class="op">=</span> <span class="fl">95</span>, y <span class="op">=</span> <span class="fl">125</span>,</span>
<span>    label <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span><span class="op">(</span><span class="st">"t = "</span>, <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="va">test_statistic</span>, <span class="fl">2</span><span class="op">)</span>, <span class="st">"\n p = "</span>, <span class="va">p_value</span><span class="op">)</span>,</span>
<span>    size <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">rel</a></span><span class="op">(</span><span class="fl">8</span><span class="op">)</span>, color<span class="op">=</span><span class="st">"grey30"</span></span>
<span>    <span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"IQ Score"</span>, y <span class="op">=</span> <span class="cn">NULL</span>, title <span class="op">=</span> <span class="cn">NULL</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="hypothesis_testing_r_files/figure-html/high-achievers-sim-test-1.png" class="img-fluid" width="960"></p>
</div>
</div>
<p>I think that one of the main strengths of this approach is the intuition it gives us for how hypothesis testing really works. By going through the process step-by-step, we can see what we are doing more easily. We compute our test statistic, which is some summary measure of the data (in this case the mean value), before simulating a null distribution under the assumption that there is no difference between our high achievers and the population. We do this by specifying the data we are testing (the response variable), stating our null hypothesis (that we are carrying out a test using a point estimate, and that the mean of the null is 100), and generating a distribution by taking 1000 bootstrap samples (where sample size is equal to our input and samples are drawn from our data with replacement).</p>
<p>Having built a null distribution, we can compare our test statistic against that null and see how extreme it appears to be if the assumption that the null hypothesis is true is correct. We can quantify this by computing a p-value, which is just a measure of the proportion of values in our null distribution that are at least as extreme as the test statistic. In the above example, because we are carrying out a one-tailed test (<code>direction = "greater"</code>), we would just need to filter the null distribution for values equal to or greater than our sample mean. If we were carrying out a two-tailed test, we would have to calculate the absolute distance of all values from the null mean, and then filter for all values equal to or greater than the difference between our sample mean and the null mean.</p>
<p>To further illustrate this workflow, below is the chi-squared test equivalent.</p>
<div class="cell" data-hash="hypothesis_testing_r_cache/html/chi-squared-sim-test_a7b944b1cdb803567a8a09838a6433b0">
<div class="sourceCode" id="cb23"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># calculate test statistic</span></span>
<span><span class="va">chisq_statistic</span> <span class="op">&lt;-</span> </span>
<span>  <span class="va">baldness_survey</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://infer.tidymodels.org/reference/specify.html">specify</a></span><span class="op">(</span><span class="va">education</span> <span class="op">~</span> <span class="va">hair_status</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://infer.tidymodels.org/reference/hypothesize.html">hypothesize</a></span><span class="op">(</span>null <span class="op">=</span> <span class="st">"independence"</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://infer.tidymodels.org/reference/calculate.html">calculate</a></span><span class="op">(</span>stat <span class="op">=</span> <span class="st">"Chisq"</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># generate null distribution</span></span>
<span><span class="va">chisq_null</span> <span class="op">&lt;-</span> </span>
<span>  <span class="va">baldness_survey</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://infer.tidymodels.org/reference/specify.html">specify</a></span><span class="op">(</span><span class="va">education</span> <span class="op">~</span> <span class="va">hair_status</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://infer.tidymodels.org/reference/hypothesize.html">hypothesize</a></span><span class="op">(</span>null <span class="op">=</span> <span class="st">"independence"</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://infer.tidymodels.org/reference/generate.html">generate</a></span><span class="op">(</span>reps <span class="op">=</span> <span class="fl">1000</span>, type <span class="op">=</span> <span class="st">"permute"</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://infer.tidymodels.org/reference/calculate.html">calculate</a></span><span class="op">(</span>stat <span class="op">=</span> <span class="st">"Chisq"</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># calculate the p value from the test statistic and null distribution</span></span>
<span><span class="va">chisq_p</span> <span class="op">&lt;-</span></span>
<span>  <span class="va">chisq_null</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://infer.tidymodels.org/reference/get_p_value.html">get_p_value</a></span><span class="op">(</span><span class="va">chisq_statistic</span>, direction <span class="op">=</span> <span class="st">"greater"</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># visualize the null distribution and test statistic</span></span>
<span><span class="va">chisq_null</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://infer.tidymodels.org/reference/visualize.html">visualize</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://infer.tidymodels.org/reference/shade_p_value.html">shade_p_value</a></span><span class="op">(</span><span class="va">chisq_statistic</span>, direction <span class="op">=</span> <span class="cn">NULL</span>, color <span class="op">=</span> <span class="st">"#00A499"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_abline.html">geom_hline</a></span><span class="op">(</span>yintercept <span class="op">=</span> <span class="fl">0</span>, colour <span class="op">=</span> <span class="st">"#333333"</span>, linewidth <span class="op">=</span> <span class="fl">1</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/annotate.html">annotate</a></span><span class="op">(</span></span>
<span>    <span class="st">"text"</span>, x <span class="op">=</span> <span class="fl">7.5</span>, y <span class="op">=</span> <span class="fl">250</span>,</span>
<span>    label <span class="op">=</span> </span>
<span>      <span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span><span class="op">(</span><span class="st">"χ2 = "</span>, <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="va">chisq_statistic</span><span class="op">$</span><span class="va">stat</span>, <span class="fl">2</span><span class="op">)</span>,</span>
<span>             <span class="st">"\n p = "</span>, <span class="va">chisq_p</span><span class="op">)</span>,</span>
<span>    size <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">rel</a></span><span class="op">(</span><span class="fl">8</span><span class="op">)</span>, color<span class="op">=</span><span class="st">"grey30"</span></span>
<span>    <span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Chi-Squared Statistic"</span>, y <span class="op">=</span> <span class="cn">NULL</span>, title <span class="op">=</span> <span class="cn">NULL</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="hypothesis_testing_r_files/figure-html/chi-squared-sim-test-1.png" class="img-fluid" width="960"></p>
</div>
</div>
<p>As discussed above, the simulation-based approach to hypothesis testing involves carrying out the processes in the hypothesis test more explicitly, and this helps us gain intuition for what we are doing. This also forces us to think about how we specify and compute our test. It’s pretty easy to build a t-test without really getting as far as actually checking if it is the right approach, and you don’t need to think long and hard about exactly what is going on when you run a t-test. Downey’s “There is only one test” framework, and the <a href="https://github.com/tidymodels/infer">infer</a> implementation, forces you to think about what you are doing and to be a little more deliberate about your choices.</p>
</section></section><section id="next-steps" class="level2" data-number="6.5"><h2 data-number="6.5" class="anchored" data-anchor-id="next-steps">
<span class="header-section-number">6.5</span> Next Steps</h2>
<p>The goal for this chapter is that readers come away with an understanding of the significant limitations of null hypothesis significance testing and the more robust approaches to testing hypotheses, and, more importantly, estimating meaningful effects.</p>
<p>I hope that this chapter has helped set people up reasonably well when carrying out tests. Equally, I hope that they will consider the alternatives, perhaps gradually weaning themselves off this bad habit and moving towards the big, wide world of estimation.</p>
<p>That big wide world is, I believe, better served by regression models than statistical tests. While regression modelling is far from sufficient for robust estimation, it is a better starting point than statistical tests, because the structure of regression modelling places more emphasis on the effect size. Further, estimating effect sizes does not rule out the use of statistical tests, but it does require redirecting our focus and making sure to treat the magnitude and direction of effect size as the most important part of the analysis. The premise of statistical tests is that they test for the existence of an effect, and while packages like {infer} frame test outputs in a way that makes using statistical tests for these purposes, it does still require a little work to think about about the results of statistical tests in these terms. Further, I think that regression modelling gives a lot more flexibility when we are attempting to estimate an effect as precisely as possible, and the process and resulting outputs of a regression model lend themselves more naturally to a focus that steers away from hypothesis testing and towards estimating effects.</p>
<p>I think it is important to stress the distinction here between the null hypothesis testing framework and the statistical tests used to carry them out. The tests themselves are not really the problem. However, they are closely tied to null hypothesis testing. Ultimately, the statistical tests discussed in this chapter (and many more) are just special cases of linear models <span class="citation" data-cites="lindelov2019">(<a href="references.html#ref-lindelov2019" role="doc-biblioref">Lindeløv 2019</a>)</span>, and the results in both will be identical <span class="citation" data-cites="zablotski2019">(<a href="references.html#ref-zablotski2019" role="doc-biblioref">Zablotski 2019</a>)</span> (if not the way the outputs are presented), so the same things can be achieved with either approach, but regression modelling offers more flexibility, allows for the layering of complexity/precision in estimates, and the way regression outputs are framed are generally a little more balanced. Treating regressions as the first point of call for inferential statistics is not a necessary prerequisite for “doing things the right way”, but doing things the right way becomes easier, because it is easier frame everything in terms of the magnitude and direction of effects.</p>
</section><section id="resources" class="level2" data-number="6.6"><h2 data-number="6.6" class="anchored" data-anchor-id="resources">
<span class="header-section-number">6.6</span> Resources</h2>
<ul>
<li><a href="https://infer.tidymodels.org/">{infer}</a></li>
<li><a href="https://seeing-theory.brown.edu/">Seeing Theory</a></li>
<li><a href="https://www.jwilber.me/permutationtest/">The Permutation Test</a></li>
<li><a href="http://allendowney.blogspot.com/2016/06/there-is-still-only-one-test.html">There is Only One Test</a></li>
<li><a href="http://allendowney.blogspot.com/2011/06/more-hypotheses-less-trivia.html">More Hypotheses, Less Trivia</a></li>
<li><a href="https://thomasleeper.com/Rcourse/Tutorials/permutationtests.html">Permutation Tests</a></li>
<li><a href="https://medium.com/analytics-vidhya/permutation-test-as-an-alternative-to-two-sample-t-test-using-r-9f5da921bc95">Permutation Test as an Alternative to Two-Sample T-Test Using R</a></li>
<li><a href="https://deliveroo.engineering/2018/12/07/monte-carlo-power-analysis.html">Power Analysis</a></li>
<li><a href="https://hookedondata.org/posts/2023-04-19-recommended-resources-for-ab-testing">Recommended Resources for A/B Testing</a></li>
<li><a href="https://elevanth.org/blog/2023/07/17/none-of-the-above/">McElreath - None of the Above</a></li>
<li><a href="https://nyu-cdsc.github.io/learningr/assets/simulation.pdf">Introduction to Scientific Programming and Simulations in R</a></li>
</ul>


<div id="refs" class="references csl-bib-body hanging-indent" role="list" style="display: none">
<div id="ref-aschwanden2015" class="csl-entry" role="listitem">
Aschwanden, Christie. 2015. <span>“Science Isn’t Broken: It’s Just a Hell of a Lot Harder Than We Give It Credit For.”</span> FiveThirtyEight. <a href="https://fivethirtyeight.com/features/science-isnt-broken/">https://fivethirtyeight.com/features/science-isnt-broken/</a>.
</div>
<div id="ref-aschwanden2016" class="csl-entry" role="listitem">
———. 2016. <span>“Statisticians Found One Thing They Can Agree on: It’s Time to Stop Misusing p-Values.”</span> FiveThirtyEight. <a href="https://fivethirtyeight.com/features/statisticians-found-one-thing-they-can-agree-on-its-time-to-stop-misusing-p-values/">https://fivethirtyeight.com/features/statisticians-found-one-thing-they-can-agree-on-its-time-to-stop-misusing-p-values/</a>.
</div>
<div id="ref-blackwell2023" class="csl-entry" role="listitem">
Blackwell, Matthew. 2023. <span>“A User’s Guide to Statistical Inference and Regression.”</span> <a href="https://mattblackwell.github.io/gov2002-book/">https://mattblackwell.github.io/gov2002-book/</a>.
</div>
<div id="ref-fisher1956" class="csl-entry" role="listitem">
Fisher, Ronald A. 1956. <span>“Statistical Methods and Scientific Inference.”</span>
</div>
<div id="ref-gelman2016" class="csl-entry" role="listitem">
Gelman, Andrew. 2016. <span>“The Problems with p-Values Are Not Just with p-Values.”</span> <em>The American Statistician</em> 70. <a href="http://www.tandfonline.com/doi/full/10.1080/00031305.2016.1154108">http://www.tandfonline.com/doi/full/10.1080/00031305.2016.1154108</a>.
</div>
<div id="ref-gelman2020" class="csl-entry" role="listitem">
Gelman, Andrew, Jennifer Hill, and Aki Vehtari Vehtari. 2020. <em>Regression and Other Stories</em>. Cambridge University Press.
</div>
<div id="ref-gelman2021" class="csl-entry" role="listitem">
Gelman, Andrew, and Eric Loken. 2021. <span>“The Statistical Crisis in Science.”</span> <em>American Scientist</em> 102 (6): 460. <a href="https://doi.org/10.1511/2014.111.460">https://doi.org/10.1511/2014.111.460</a>.
</div>
<div id="ref-gelman2006" class="csl-entry" role="listitem">
Gelman, Andrew, and Hal Stern. 2006. <span>“The Difference Between "Significant" and "Not Significant" Is Not Itself Statistically Significant.”</span> <em>The American Statistician</em> 60 (4): 328–31.
</div>
<div id="ref-greenland2016" class="csl-entry" role="listitem">
Greenland, Sander, Stephen J. Senn, Kenneth J. Rothman, John B. Carlin, Charles Poole, Steven N. Goodman, and Douglas G. Altman. 2016. <span>“Statistical Tests, p-Values, Confidence Intervals, and Power: A Guide to Misinterpretations.”</span> <em>European Journal of Epidemiology</em> 31: 337–50.
</div>
<div id="ref-lakens2022" class="csl-entry" role="listitem">
Lakens, Daniel. 2022. <em>Improving Your Statistical Inferences</em>. <a href="https://doi.org/10.5281/zenodo.6409077">https://doi.org/10.5281/zenodo.6409077</a>.
</div>
<div id="ref-lindelov2019" class="csl-entry" role="listitem">
Lindeløv, Jonas Kristoffer. 2019. <span>“Common Statistical Tests Are Linear Models.”</span> <a href="https://lindeloev.github.io/tests-as-linear/">https://lindeloev.github.io/tests-as-linear/</a>.
</div>
<div id="ref-mcelreath2023" class="csl-entry" role="listitem">
McElreath, Richard. 2023. <span>“None of the Above.”</span> <a href="https://elevanth.org/blog/2023/07/17/none-of-the-above/">https://elevanth.org/blog/2023/07/17/none-of-the-above/</a>.
</div>
<div id="ref-poole2022" class="csl-entry" role="listitem">
Poole, Charles. 2022. <span>“The Statistical Arc of Epidemiology.”</span> Presented at the "What is the Value of the P-Value?" Panel Discussion, Cosponsored by UNC TraCS, Duke University, and Wake Forest University CTSA Biostatistics, Epidemiology and Research Design (BERD) Cores.
</div>
<div id="ref-popper1935" class="csl-entry" role="listitem">
Popper, Karl. 1935. <em>The Logic of Scientific Discovery</em>. Routledge.
</div>
<div id="ref-sinikumpu2021" class="csl-entry" role="listitem">
Sinikumpu, Suvi-Päivikki, Jari Jokelainen, Juha Auvinena, Markku Timonen, and Laura Huilaja. 2021. <span>“Association Between Psychosocial Distress, Sexual Disorders, Self-Esteem and Quality of Life with Male Androgenetic Alopecia: A Population-Based Study with Men at Age 46.”</span> <em>BMJ Open</em> 11 (12).
</div>
<div id="ref-wasserstein2016" class="csl-entry" role="listitem">
Wasserstein, Ronald L., and Nicole A. Lazar. 2016. <span>“The ASA Statement on p-Values: Context, Process, and Purpose.”</span> <em>The American Statistician</em> 70 (2): 129–33. <a href="https://doi.org/10.1080/00031305.2016.1154108">https://doi.org/10.1080/00031305.2016.1154108</a>.
</div>
<div id="ref-wasserstein2019" class="csl-entry" role="listitem">
Wasserstein, Ronald L., Allen L. Schirm, and Nicole A. Lazar. 2019. <span>“Moving to a World Beyond "p &lt; 0.05".”</span> <em>The American Statistician</em> 73 (sup1): 1–19. <a href="https://doi.org/10.1080/00031305.2019.1583913">https://doi.org/10.1080/00031305.2019.1583913</a>.
</div>
<div id="ref-zablotski2019" class="csl-entry" role="listitem">
Zablotski, Yury. 2019. <span>“Statistical Tests Vs. Linear Regression.”</span> <a href="https://yury-zablotski.netlify.app/post/statistical-tests-vs-linear-regression/">https://yury-zablotski.netlify.app/post/statistical-tests-vs-linear-regression/</a>.
</div>
</div>
</section><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><hr>
<ol>
<li id="fn1"><p>I could stubbornly refuse to write about hypothesis tests, like covering my eyes and ears and screaming as someone asks me how to do a t-test properly, but something tells me that isn’t going to stop them happening. I would rather give someone all the necessary resources (or at least as much as is possible in a relatively limited guide like this), and hope it helps them improve the way they go about asking questions of data.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>I won’t discuss all 25 misinterpretations that <span class="citation" data-cites="greenland2016">Greenland et al. (<a href="references.html#ref-greenland2016" role="doc-biblioref">2016</a>)</span> discuss, because that would be overkill here. For anyone that is interested in learning more about the problems with p-values, I’d recommend going straight to the source and reading their paper.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>The probability that a p-value represents are specific to the statistical model we are specifying. It’s important to remember that violations of our assumptions in specifying our model can bias the p-value and invalidate our results.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>I’m assuming that anyone following this advice has good intentions, and is not looking to cheat their way to the results they want. Someone wanting to achieve this is going to find a way to do it regardless.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>If you are unclear on some of the foundations that underpin what I’m discussing here, I’d recommend starting with StatQuest’s <a href="https://www.youtube.com/playlist?list=PLblh5JKOoLUK0FLuzwntyYI10UQFUhsY9">Statistics Fundamentals</a> YouTube playlist, and for a more detailed introduction, I would give <a href="https://crumplab.com/statistics"><em>Answering Questions With Data</em></a> a try.<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p>The Neyman-Pearson approach to interpreting p-values in significance tests would conclude that a p-value less than a certain threshold, often p &lt; 0.05, is not statistically significant, and would therefore fail to reject the null hypothesis. We are refraining from using this framing here because I think this approach does more harm than good.<a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn7"><p>Standard deviation can be computed from standard error by multiplying the standard error by the square root of the sample size. The formula for this is as follows: <span class="math display">\[\sigma = SE \times \sqrt{n}\]</span><a href="#fnref7" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn8"><p>Using only five observations is less than ideal, but given that what we are doing is just illustrative, this will work fine.<a href="#fnref8" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn9"><p>We have used the <a href="https://debruine.github.io/faux/"><code>{faux}</code></a> package to simulate this data because simulating two variables that are related to each other is a little more involved.<a href="#fnref9" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol></section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./eda_r.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Exploratory Data Analysis</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./linear_regression_r.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Linear Regression</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center"><a href="https://python-data-science-guides.netlify.app"> Python Data Science Guides</a> <i class="fa-brands fa-python fa-xl" aria-label="python"></i></div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>


</body></html>